// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private short actorId;
     private String firstName;
     private String lastName;
     private Timestamp lastUpdate;
     private Set filmActors = new HashSet(0);

    public Actor() {
    }

	
    public Actor(short actorId, String firstName, String lastName, Timestamp lastUpdate) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
    }
    public Actor(short actorId, String firstName, String lastName, Timestamp lastUpdate, Set filmActors) {
       this.actorId = actorId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.lastUpdate = lastUpdate;
       this.filmActors = filmActors;
    }
   
    public short getActorId() {
        return this.actorId;
    }
    
    public void setActorId(short actorId) {
        this.actorId = actorId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getFilmActors() {
        return this.filmActors;
    }
    
    public void setFilmActors(Set filmActors) {
        this.filmActors = filmActors;
    }




}


