// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private byte categoryId;
     private String name;
     private Timestamp lastUpdate;
     private Set filmCategories = new HashSet(0);

    public Category() {
    }

	
    public Category(byte categoryId, String name, Timestamp lastUpdate) {
        this.categoryId = categoryId;
        this.name = name;
        this.lastUpdate = lastUpdate;
    }
    public Category(byte categoryId, String name, Timestamp lastUpdate, Set filmCategories) {
       this.categoryId = categoryId;
       this.name = name;
       this.lastUpdate = lastUpdate;
       this.filmCategories = filmCategories;
    }
   
    public byte getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(byte categoryId) {
        this.categoryId = categoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getFilmCategories() {
        return this.filmCategories;
    }
    
    public void setFilmCategories(Set filmCategories) {
        this.filmCategories = filmCategories;
    }




}


