// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * CheckConstraintsId generated by hbm2java
 */
public class CheckConstraintsId  implements java.io.Serializable {


     private String checkClause;
     private String constraintCatalog;
     private String constraintName;
     private String constraintSchema;

    public CheckConstraintsId() {
    }

    public CheckConstraintsId(String checkClause, String constraintCatalog, String constraintName, String constraintSchema) {
       this.checkClause = checkClause;
       this.constraintCatalog = constraintCatalog;
       this.constraintName = constraintName;
       this.constraintSchema = constraintSchema;
    }
   
    public String getCheckClause() {
        return this.checkClause;
    }
    
    public void setCheckClause(String checkClause) {
        this.checkClause = checkClause;
    }
    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }
    
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }
    public String getConstraintName() {
        return this.constraintName;
    }
    
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }
    public String getConstraintSchema() {
        return this.constraintSchema;
    }
    
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CheckConstraintsId) ) return false;
		 CheckConstraintsId castOther = ( CheckConstraintsId ) other; 
         
		 return ( (this.getCheckClause()==castOther.getCheckClause()) || ( this.getCheckClause()!=null && castOther.getCheckClause()!=null && this.getCheckClause().equals(castOther.getCheckClause()) ) )
 && ( (this.getConstraintCatalog()==castOther.getConstraintCatalog()) || ( this.getConstraintCatalog()!=null && castOther.getConstraintCatalog()!=null && this.getConstraintCatalog().equals(castOther.getConstraintCatalog()) ) )
 && ( (this.getConstraintName()==castOther.getConstraintName()) || ( this.getConstraintName()!=null && castOther.getConstraintName()!=null && this.getConstraintName().equals(castOther.getConstraintName()) ) )
 && ( (this.getConstraintSchema()==castOther.getConstraintSchema()) || ( this.getConstraintSchema()!=null && castOther.getConstraintSchema()!=null && this.getConstraintSchema().equals(castOther.getConstraintSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCheckClause() == null ? 0 : this.getCheckClause().hashCode() );
        result = 37 * result + ( getConstraintCatalog() == null ? 0 : this.getConstraintCatalog().hashCode() );
        result = 37 * result + ( getConstraintName() == null ? 0 : this.getConstraintName().hashCode() );
        result = 37 * result + ( getConstraintSchema() == null ? 0 : this.getConstraintSchema().hashCode() );
         return result;
   }   


}


