// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * CheckConstraints generated by hbm2java
 */
public class CheckConstraints  implements java.io.Serializable {


     private CheckConstraintsId id;

    public CheckConstraints() {
    }

    public CheckConstraints(CheckConstraintsId id) {
       this.id = id;
    }
   
    public CheckConstraintsId getId() {
        return this.id;
    }
    
    public void setId(CheckConstraintsId id) {
        this.id = id;
    }




}


