// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private short cityId;
     private Country country;
     private String city;
     private Timestamp lastUpdate;
     private Set addresses = new HashSet(0);

    public City() {
    }

	
    public City(short cityId, Country country, String city, Timestamp lastUpdate) {
        this.cityId = cityId;
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
    }
    public City(short cityId, Country country, String city, Timestamp lastUpdate, Set addresses) {
       this.cityId = cityId;
       this.country = country;
       this.city = city;
       this.lastUpdate = lastUpdate;
       this.addresses = addresses;
    }
   
    public short getCityId() {
        return this.cityId;
    }
    
    public void setCityId(short cityId) {
        this.cityId = cityId;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


