// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Collations generated by hbm2java
 */
public class Collations  implements java.io.Serializable {


     private CollationsId id;

    public Collations() {
    }

    public Collations(CollationsId id) {
       this.id = id;
    }
   
    public CollationsId getId() {
        return this.id;
    }
    
    public void setId(CollationsId id) {
        this.id = id;
    }




}


