// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * CollationsId generated by hbm2java
 */
public class CollationsId  implements java.io.Serializable {


     private String collationCatalog;
     private String collationName;
     private String collationSchema;
     private String languageTag;
     private String padAttribute;

    public CollationsId() {
    }

    public CollationsId(String collationCatalog, String collationName, String collationSchema, String languageTag, String padAttribute) {
       this.collationCatalog = collationCatalog;
       this.collationName = collationName;
       this.collationSchema = collationSchema;
       this.languageTag = languageTag;
       this.padAttribute = padAttribute;
    }
   
    public String getCollationCatalog() {
        return this.collationCatalog;
    }
    
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }
    public String getCollationName() {
        return this.collationName;
    }
    
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }
    public String getCollationSchema() {
        return this.collationSchema;
    }
    
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }
    public String getLanguageTag() {
        return this.languageTag;
    }
    
    public void setLanguageTag(String languageTag) {
        this.languageTag = languageTag;
    }
    public String getPadAttribute() {
        return this.padAttribute;
    }
    
    public void setPadAttribute(String padAttribute) {
        this.padAttribute = padAttribute;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CollationsId) ) return false;
		 CollationsId castOther = ( CollationsId ) other; 
         
		 return ( (this.getCollationCatalog()==castOther.getCollationCatalog()) || ( this.getCollationCatalog()!=null && castOther.getCollationCatalog()!=null && this.getCollationCatalog().equals(castOther.getCollationCatalog()) ) )
 && ( (this.getCollationName()==castOther.getCollationName()) || ( this.getCollationName()!=null && castOther.getCollationName()!=null && this.getCollationName().equals(castOther.getCollationName()) ) )
 && ( (this.getCollationSchema()==castOther.getCollationSchema()) || ( this.getCollationSchema()!=null && castOther.getCollationSchema()!=null && this.getCollationSchema().equals(castOther.getCollationSchema()) ) )
 && ( (this.getLanguageTag()==castOther.getLanguageTag()) || ( this.getLanguageTag()!=null && castOther.getLanguageTag()!=null && this.getLanguageTag().equals(castOther.getLanguageTag()) ) )
 && ( (this.getPadAttribute()==castOther.getPadAttribute()) || ( this.getPadAttribute()!=null && castOther.getPadAttribute()!=null && this.getPadAttribute().equals(castOther.getPadAttribute()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCollationCatalog() == null ? 0 : this.getCollationCatalog().hashCode() );
        result = 37 * result + ( getCollationName() == null ? 0 : this.getCollationName().hashCode() );
        result = 37 * result + ( getCollationSchema() == null ? 0 : this.getCollationSchema().hashCode() );
        result = 37 * result + ( getLanguageTag() == null ? 0 : this.getLanguageTag().hashCode() );
        result = 37 * result + ( getPadAttribute() == null ? 0 : this.getPadAttribute().hashCode() );
         return result;
   }   


}


