// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ColumnsId generated by hbm2java
 */
public class ColumnsId  implements java.io.Serializable {


     private Long characterMaximumLength;
     private Long characterOctetLength;
     private String characterSetCatalog;
     private String characterSetName;
     private String characterSetSchema;
     private String collationCatalog;
     private String collationName;
     private String collationSchema;
     private String columnDefault;
     private String columnName;
     private String columnOnUpdate;
     private String dataType;
     private Integer datetimePrecision;
     private String declaredDataType;
     private Integer declaredNumericPrecision;
     private Integer declaredNumericScale;
     private Boolean defaultOnNull;
     private String domainCatalog;
     private String domainName;
     private String domainSchema;
     private String dtdIdentifier;
     private String generationExpression;
     private Integer geometrySrid;
     private String geometryType;
     private Long identityBase;
     private Long identityCache;
     private String identityCycle;
     private String identityGeneration;
     private Long identityIncrement;
     private Long identityMaximum;
     private Long identityMinimum;
     private Long identityStart;
     private Integer intervalPrecision;
     private String intervalType;
     private String isGenerated;
     private String isIdentity;
     private String isNullable;
     private Boolean isVisible;
     private Integer maximumCardinality;
     private Integer numericPrecision;
     private Integer numericPrecisionRadix;
     private Integer numericScale;
     private Integer ordinalPosition;
     private String remarks;
     private Integer selectivity;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;

    public ColumnsId() {
    }

    public ColumnsId(Long characterMaximumLength, Long characterOctetLength, String characterSetCatalog, String characterSetName, String characterSetSchema, String collationCatalog, String collationName, String collationSchema, String columnDefault, String columnName, String columnOnUpdate, String dataType, Integer datetimePrecision, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, Boolean defaultOnNull, String domainCatalog, String domainName, String domainSchema, String dtdIdentifier, String generationExpression, Integer geometrySrid, String geometryType, Long identityBase, Long identityCache, String identityCycle, String identityGeneration, Long identityIncrement, Long identityMaximum, Long identityMinimum, Long identityStart, Integer intervalPrecision, String intervalType, String isGenerated, String isIdentity, String isNullable, Boolean isVisible, Integer maximumCardinality, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, Integer ordinalPosition, String remarks, Integer selectivity, String tableCatalog, String tableName, String tableSchema) {
       this.characterMaximumLength = characterMaximumLength;
       this.characterOctetLength = characterOctetLength;
       this.characterSetCatalog = characterSetCatalog;
       this.characterSetName = characterSetName;
       this.characterSetSchema = characterSetSchema;
       this.collationCatalog = collationCatalog;
       this.collationName = collationName;
       this.collationSchema = collationSchema;
       this.columnDefault = columnDefault;
       this.columnName = columnName;
       this.columnOnUpdate = columnOnUpdate;
       this.dataType = dataType;
       this.datetimePrecision = datetimePrecision;
       this.declaredDataType = declaredDataType;
       this.declaredNumericPrecision = declaredNumericPrecision;
       this.declaredNumericScale = declaredNumericScale;
       this.defaultOnNull = defaultOnNull;
       this.domainCatalog = domainCatalog;
       this.domainName = domainName;
       this.domainSchema = domainSchema;
       this.dtdIdentifier = dtdIdentifier;
       this.generationExpression = generationExpression;
       this.geometrySrid = geometrySrid;
       this.geometryType = geometryType;
       this.identityBase = identityBase;
       this.identityCache = identityCache;
       this.identityCycle = identityCycle;
       this.identityGeneration = identityGeneration;
       this.identityIncrement = identityIncrement;
       this.identityMaximum = identityMaximum;
       this.identityMinimum = identityMinimum;
       this.identityStart = identityStart;
       this.intervalPrecision = intervalPrecision;
       this.intervalType = intervalType;
       this.isGenerated = isGenerated;
       this.isIdentity = isIdentity;
       this.isNullable = isNullable;
       this.isVisible = isVisible;
       this.maximumCardinality = maximumCardinality;
       this.numericPrecision = numericPrecision;
       this.numericPrecisionRadix = numericPrecisionRadix;
       this.numericScale = numericScale;
       this.ordinalPosition = ordinalPosition;
       this.remarks = remarks;
       this.selectivity = selectivity;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public Long getCharacterMaximumLength() {
        return this.characterMaximumLength;
    }
    
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }
    public Long getCharacterOctetLength() {
        return this.characterOctetLength;
    }
    
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }
    public String getCharacterSetCatalog() {
        return this.characterSetCatalog;
    }
    
    public void setCharacterSetCatalog(String characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }
    public String getCharacterSetName() {
        return this.characterSetName;
    }
    
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }
    public String getCharacterSetSchema() {
        return this.characterSetSchema;
    }
    
    public void setCharacterSetSchema(String characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }
    public String getCollationCatalog() {
        return this.collationCatalog;
    }
    
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }
    public String getCollationName() {
        return this.collationName;
    }
    
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }
    public String getCollationSchema() {
        return this.collationSchema;
    }
    
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }
    public String getColumnDefault() {
        return this.columnDefault;
    }
    
    public void setColumnDefault(String columnDefault) {
        this.columnDefault = columnDefault;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getColumnOnUpdate() {
        return this.columnOnUpdate;
    }
    
    public void setColumnOnUpdate(String columnOnUpdate) {
        this.columnOnUpdate = columnOnUpdate;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public Integer getDatetimePrecision() {
        return this.datetimePrecision;
    }
    
    public void setDatetimePrecision(Integer datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }
    public String getDeclaredDataType() {
        return this.declaredDataType;
    }
    
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }
    public Integer getDeclaredNumericPrecision() {
        return this.declaredNumericPrecision;
    }
    
    public void setDeclaredNumericPrecision(Integer declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }
    public Integer getDeclaredNumericScale() {
        return this.declaredNumericScale;
    }
    
    public void setDeclaredNumericScale(Integer declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }
    public Boolean getDefaultOnNull() {
        return this.defaultOnNull;
    }
    
    public void setDefaultOnNull(Boolean defaultOnNull) {
        this.defaultOnNull = defaultOnNull;
    }
    public String getDomainCatalog() {
        return this.domainCatalog;
    }
    
    public void setDomainCatalog(String domainCatalog) {
        this.domainCatalog = domainCatalog;
    }
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    public String getDomainSchema() {
        return this.domainSchema;
    }
    
    public void setDomainSchema(String domainSchema) {
        this.domainSchema = domainSchema;
    }
    public String getDtdIdentifier() {
        return this.dtdIdentifier;
    }
    
    public void setDtdIdentifier(String dtdIdentifier) {
        this.dtdIdentifier = dtdIdentifier;
    }
    public String getGenerationExpression() {
        return this.generationExpression;
    }
    
    public void setGenerationExpression(String generationExpression) {
        this.generationExpression = generationExpression;
    }
    public Integer getGeometrySrid() {
        return this.geometrySrid;
    }
    
    public void setGeometrySrid(Integer geometrySrid) {
        this.geometrySrid = geometrySrid;
    }
    public String getGeometryType() {
        return this.geometryType;
    }
    
    public void setGeometryType(String geometryType) {
        this.geometryType = geometryType;
    }
    public Long getIdentityBase() {
        return this.identityBase;
    }
    
    public void setIdentityBase(Long identityBase) {
        this.identityBase = identityBase;
    }
    public Long getIdentityCache() {
        return this.identityCache;
    }
    
    public void setIdentityCache(Long identityCache) {
        this.identityCache = identityCache;
    }
    public String getIdentityCycle() {
        return this.identityCycle;
    }
    
    public void setIdentityCycle(String identityCycle) {
        this.identityCycle = identityCycle;
    }
    public String getIdentityGeneration() {
        return this.identityGeneration;
    }
    
    public void setIdentityGeneration(String identityGeneration) {
        this.identityGeneration = identityGeneration;
    }
    public Long getIdentityIncrement() {
        return this.identityIncrement;
    }
    
    public void setIdentityIncrement(Long identityIncrement) {
        this.identityIncrement = identityIncrement;
    }
    public Long getIdentityMaximum() {
        return this.identityMaximum;
    }
    
    public void setIdentityMaximum(Long identityMaximum) {
        this.identityMaximum = identityMaximum;
    }
    public Long getIdentityMinimum() {
        return this.identityMinimum;
    }
    
    public void setIdentityMinimum(Long identityMinimum) {
        this.identityMinimum = identityMinimum;
    }
    public Long getIdentityStart() {
        return this.identityStart;
    }
    
    public void setIdentityStart(Long identityStart) {
        this.identityStart = identityStart;
    }
    public Integer getIntervalPrecision() {
        return this.intervalPrecision;
    }
    
    public void setIntervalPrecision(Integer intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }
    public String getIntervalType() {
        return this.intervalType;
    }
    
    public void setIntervalType(String intervalType) {
        this.intervalType = intervalType;
    }
    public String getIsGenerated() {
        return this.isGenerated;
    }
    
    public void setIsGenerated(String isGenerated) {
        this.isGenerated = isGenerated;
    }
    public String getIsIdentity() {
        return this.isIdentity;
    }
    
    public void setIsIdentity(String isIdentity) {
        this.isIdentity = isIdentity;
    }
    public String getIsNullable() {
        return this.isNullable;
    }
    
    public void setIsNullable(String isNullable) {
        this.isNullable = isNullable;
    }
    public Boolean getIsVisible() {
        return this.isVisible;
    }
    
    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }
    public Integer getMaximumCardinality() {
        return this.maximumCardinality;
    }
    
    public void setMaximumCardinality(Integer maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }
    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }
    
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }
    public Integer getNumericPrecisionRadix() {
        return this.numericPrecisionRadix;
    }
    
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }
    public Integer getNumericScale() {
        return this.numericScale;
    }
    
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }
    public Integer getOrdinalPosition() {
        return this.ordinalPosition;
    }
    
    public void setOrdinalPosition(Integer ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getSelectivity() {
        return this.selectivity;
    }
    
    public void setSelectivity(Integer selectivity) {
        this.selectivity = selectivity;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ColumnsId) ) return false;
		 ColumnsId castOther = ( ColumnsId ) other; 
         
		 return ( (this.getCharacterMaximumLength()==castOther.getCharacterMaximumLength()) || ( this.getCharacterMaximumLength()!=null && castOther.getCharacterMaximumLength()!=null && this.getCharacterMaximumLength().equals(castOther.getCharacterMaximumLength()) ) )
 && ( (this.getCharacterOctetLength()==castOther.getCharacterOctetLength()) || ( this.getCharacterOctetLength()!=null && castOther.getCharacterOctetLength()!=null && this.getCharacterOctetLength().equals(castOther.getCharacterOctetLength()) ) )
 && ( (this.getCharacterSetCatalog()==castOther.getCharacterSetCatalog()) || ( this.getCharacterSetCatalog()!=null && castOther.getCharacterSetCatalog()!=null && this.getCharacterSetCatalog().equals(castOther.getCharacterSetCatalog()) ) )
 && ( (this.getCharacterSetName()==castOther.getCharacterSetName()) || ( this.getCharacterSetName()!=null && castOther.getCharacterSetName()!=null && this.getCharacterSetName().equals(castOther.getCharacterSetName()) ) )
 && ( (this.getCharacterSetSchema()==castOther.getCharacterSetSchema()) || ( this.getCharacterSetSchema()!=null && castOther.getCharacterSetSchema()!=null && this.getCharacterSetSchema().equals(castOther.getCharacterSetSchema()) ) )
 && ( (this.getCollationCatalog()==castOther.getCollationCatalog()) || ( this.getCollationCatalog()!=null && castOther.getCollationCatalog()!=null && this.getCollationCatalog().equals(castOther.getCollationCatalog()) ) )
 && ( (this.getCollationName()==castOther.getCollationName()) || ( this.getCollationName()!=null && castOther.getCollationName()!=null && this.getCollationName().equals(castOther.getCollationName()) ) )
 && ( (this.getCollationSchema()==castOther.getCollationSchema()) || ( this.getCollationSchema()!=null && castOther.getCollationSchema()!=null && this.getCollationSchema().equals(castOther.getCollationSchema()) ) )
 && ( (this.getColumnDefault()==castOther.getColumnDefault()) || ( this.getColumnDefault()!=null && castOther.getColumnDefault()!=null && this.getColumnDefault().equals(castOther.getColumnDefault()) ) )
 && ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) )
 && ( (this.getColumnOnUpdate()==castOther.getColumnOnUpdate()) || ( this.getColumnOnUpdate()!=null && castOther.getColumnOnUpdate()!=null && this.getColumnOnUpdate().equals(castOther.getColumnOnUpdate()) ) )
 && ( (this.getDataType()==castOther.getDataType()) || ( this.getDataType()!=null && castOther.getDataType()!=null && this.getDataType().equals(castOther.getDataType()) ) )
 && ( (this.getDatetimePrecision()==castOther.getDatetimePrecision()) || ( this.getDatetimePrecision()!=null && castOther.getDatetimePrecision()!=null && this.getDatetimePrecision().equals(castOther.getDatetimePrecision()) ) )
 && ( (this.getDeclaredDataType()==castOther.getDeclaredDataType()) || ( this.getDeclaredDataType()!=null && castOther.getDeclaredDataType()!=null && this.getDeclaredDataType().equals(castOther.getDeclaredDataType()) ) )
 && ( (this.getDeclaredNumericPrecision()==castOther.getDeclaredNumericPrecision()) || ( this.getDeclaredNumericPrecision()!=null && castOther.getDeclaredNumericPrecision()!=null && this.getDeclaredNumericPrecision().equals(castOther.getDeclaredNumericPrecision()) ) )
 && ( (this.getDeclaredNumericScale()==castOther.getDeclaredNumericScale()) || ( this.getDeclaredNumericScale()!=null && castOther.getDeclaredNumericScale()!=null && this.getDeclaredNumericScale().equals(castOther.getDeclaredNumericScale()) ) )
 && ( (this.getDefaultOnNull()==castOther.getDefaultOnNull()) || ( this.getDefaultOnNull()!=null && castOther.getDefaultOnNull()!=null && this.getDefaultOnNull().equals(castOther.getDefaultOnNull()) ) )
 && ( (this.getDomainCatalog()==castOther.getDomainCatalog()) || ( this.getDomainCatalog()!=null && castOther.getDomainCatalog()!=null && this.getDomainCatalog().equals(castOther.getDomainCatalog()) ) )
 && ( (this.getDomainName()==castOther.getDomainName()) || ( this.getDomainName()!=null && castOther.getDomainName()!=null && this.getDomainName().equals(castOther.getDomainName()) ) )
 && ( (this.getDomainSchema()==castOther.getDomainSchema()) || ( this.getDomainSchema()!=null && castOther.getDomainSchema()!=null && this.getDomainSchema().equals(castOther.getDomainSchema()) ) )
 && ( (this.getDtdIdentifier()==castOther.getDtdIdentifier()) || ( this.getDtdIdentifier()!=null && castOther.getDtdIdentifier()!=null && this.getDtdIdentifier().equals(castOther.getDtdIdentifier()) ) )
 && ( (this.getGenerationExpression()==castOther.getGenerationExpression()) || ( this.getGenerationExpression()!=null && castOther.getGenerationExpression()!=null && this.getGenerationExpression().equals(castOther.getGenerationExpression()) ) )
 && ( (this.getGeometrySrid()==castOther.getGeometrySrid()) || ( this.getGeometrySrid()!=null && castOther.getGeometrySrid()!=null && this.getGeometrySrid().equals(castOther.getGeometrySrid()) ) )
 && ( (this.getGeometryType()==castOther.getGeometryType()) || ( this.getGeometryType()!=null && castOther.getGeometryType()!=null && this.getGeometryType().equals(castOther.getGeometryType()) ) )
 && ( (this.getIdentityBase()==castOther.getIdentityBase()) || ( this.getIdentityBase()!=null && castOther.getIdentityBase()!=null && this.getIdentityBase().equals(castOther.getIdentityBase()) ) )
 && ( (this.getIdentityCache()==castOther.getIdentityCache()) || ( this.getIdentityCache()!=null && castOther.getIdentityCache()!=null && this.getIdentityCache().equals(castOther.getIdentityCache()) ) )
 && ( (this.getIdentityCycle()==castOther.getIdentityCycle()) || ( this.getIdentityCycle()!=null && castOther.getIdentityCycle()!=null && this.getIdentityCycle().equals(castOther.getIdentityCycle()) ) )
 && ( (this.getIdentityGeneration()==castOther.getIdentityGeneration()) || ( this.getIdentityGeneration()!=null && castOther.getIdentityGeneration()!=null && this.getIdentityGeneration().equals(castOther.getIdentityGeneration()) ) )
 && ( (this.getIdentityIncrement()==castOther.getIdentityIncrement()) || ( this.getIdentityIncrement()!=null && castOther.getIdentityIncrement()!=null && this.getIdentityIncrement().equals(castOther.getIdentityIncrement()) ) )
 && ( (this.getIdentityMaximum()==castOther.getIdentityMaximum()) || ( this.getIdentityMaximum()!=null && castOther.getIdentityMaximum()!=null && this.getIdentityMaximum().equals(castOther.getIdentityMaximum()) ) )
 && ( (this.getIdentityMinimum()==castOther.getIdentityMinimum()) || ( this.getIdentityMinimum()!=null && castOther.getIdentityMinimum()!=null && this.getIdentityMinimum().equals(castOther.getIdentityMinimum()) ) )
 && ( (this.getIdentityStart()==castOther.getIdentityStart()) || ( this.getIdentityStart()!=null && castOther.getIdentityStart()!=null && this.getIdentityStart().equals(castOther.getIdentityStart()) ) )
 && ( (this.getIntervalPrecision()==castOther.getIntervalPrecision()) || ( this.getIntervalPrecision()!=null && castOther.getIntervalPrecision()!=null && this.getIntervalPrecision().equals(castOther.getIntervalPrecision()) ) )
 && ( (this.getIntervalType()==castOther.getIntervalType()) || ( this.getIntervalType()!=null && castOther.getIntervalType()!=null && this.getIntervalType().equals(castOther.getIntervalType()) ) )
 && ( (this.getIsGenerated()==castOther.getIsGenerated()) || ( this.getIsGenerated()!=null && castOther.getIsGenerated()!=null && this.getIsGenerated().equals(castOther.getIsGenerated()) ) )
 && ( (this.getIsIdentity()==castOther.getIsIdentity()) || ( this.getIsIdentity()!=null && castOther.getIsIdentity()!=null && this.getIsIdentity().equals(castOther.getIsIdentity()) ) )
 && ( (this.getIsNullable()==castOther.getIsNullable()) || ( this.getIsNullable()!=null && castOther.getIsNullable()!=null && this.getIsNullable().equals(castOther.getIsNullable()) ) )
 && ( (this.getIsVisible()==castOther.getIsVisible()) || ( this.getIsVisible()!=null && castOther.getIsVisible()!=null && this.getIsVisible().equals(castOther.getIsVisible()) ) )
 && ( (this.getMaximumCardinality()==castOther.getMaximumCardinality()) || ( this.getMaximumCardinality()!=null && castOther.getMaximumCardinality()!=null && this.getMaximumCardinality().equals(castOther.getMaximumCardinality()) ) )
 && ( (this.getNumericPrecision()==castOther.getNumericPrecision()) || ( this.getNumericPrecision()!=null && castOther.getNumericPrecision()!=null && this.getNumericPrecision().equals(castOther.getNumericPrecision()) ) )
 && ( (this.getNumericPrecisionRadix()==castOther.getNumericPrecisionRadix()) || ( this.getNumericPrecisionRadix()!=null && castOther.getNumericPrecisionRadix()!=null && this.getNumericPrecisionRadix().equals(castOther.getNumericPrecisionRadix()) ) )
 && ( (this.getNumericScale()==castOther.getNumericScale()) || ( this.getNumericScale()!=null && castOther.getNumericScale()!=null && this.getNumericScale().equals(castOther.getNumericScale()) ) )
 && ( (this.getOrdinalPosition()==castOther.getOrdinalPosition()) || ( this.getOrdinalPosition()!=null && castOther.getOrdinalPosition()!=null && this.getOrdinalPosition().equals(castOther.getOrdinalPosition()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getSelectivity()==castOther.getSelectivity()) || ( this.getSelectivity()!=null && castOther.getSelectivity()!=null && this.getSelectivity().equals(castOther.getSelectivity()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCharacterMaximumLength() == null ? 0 : this.getCharacterMaximumLength().hashCode() );
        result = 37 * result + ( getCharacterOctetLength() == null ? 0 : this.getCharacterOctetLength().hashCode() );
        result = 37 * result + ( getCharacterSetCatalog() == null ? 0 : this.getCharacterSetCatalog().hashCode() );
        result = 37 * result + ( getCharacterSetName() == null ? 0 : this.getCharacterSetName().hashCode() );
        result = 37 * result + ( getCharacterSetSchema() == null ? 0 : this.getCharacterSetSchema().hashCode() );
        result = 37 * result + ( getCollationCatalog() == null ? 0 : this.getCollationCatalog().hashCode() );
        result = 37 * result + ( getCollationName() == null ? 0 : this.getCollationName().hashCode() );
        result = 37 * result + ( getCollationSchema() == null ? 0 : this.getCollationSchema().hashCode() );
        result = 37 * result + ( getColumnDefault() == null ? 0 : this.getColumnDefault().hashCode() );
        result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
        result = 37 * result + ( getColumnOnUpdate() == null ? 0 : this.getColumnOnUpdate().hashCode() );
        result = 37 * result + ( getDataType() == null ? 0 : this.getDataType().hashCode() );
        result = 37 * result + ( getDatetimePrecision() == null ? 0 : this.getDatetimePrecision().hashCode() );
        result = 37 * result + ( getDeclaredDataType() == null ? 0 : this.getDeclaredDataType().hashCode() );
        result = 37 * result + ( getDeclaredNumericPrecision() == null ? 0 : this.getDeclaredNumericPrecision().hashCode() );
        result = 37 * result + ( getDeclaredNumericScale() == null ? 0 : this.getDeclaredNumericScale().hashCode() );
        result = 37 * result + ( getDefaultOnNull() == null ? 0 : this.getDefaultOnNull().hashCode() );
        result = 37 * result + ( getDomainCatalog() == null ? 0 : this.getDomainCatalog().hashCode() );
        result = 37 * result + ( getDomainName() == null ? 0 : this.getDomainName().hashCode() );
        result = 37 * result + ( getDomainSchema() == null ? 0 : this.getDomainSchema().hashCode() );
        result = 37 * result + ( getDtdIdentifier() == null ? 0 : this.getDtdIdentifier().hashCode() );
        result = 37 * result + ( getGenerationExpression() == null ? 0 : this.getGenerationExpression().hashCode() );
        result = 37 * result + ( getGeometrySrid() == null ? 0 : this.getGeometrySrid().hashCode() );
        result = 37 * result + ( getGeometryType() == null ? 0 : this.getGeometryType().hashCode() );
        result = 37 * result + ( getIdentityBase() == null ? 0 : this.getIdentityBase().hashCode() );
        result = 37 * result + ( getIdentityCache() == null ? 0 : this.getIdentityCache().hashCode() );
        result = 37 * result + ( getIdentityCycle() == null ? 0 : this.getIdentityCycle().hashCode() );
        result = 37 * result + ( getIdentityGeneration() == null ? 0 : this.getIdentityGeneration().hashCode() );
        result = 37 * result + ( getIdentityIncrement() == null ? 0 : this.getIdentityIncrement().hashCode() );
        result = 37 * result + ( getIdentityMaximum() == null ? 0 : this.getIdentityMaximum().hashCode() );
        result = 37 * result + ( getIdentityMinimum() == null ? 0 : this.getIdentityMinimum().hashCode() );
        result = 37 * result + ( getIdentityStart() == null ? 0 : this.getIdentityStart().hashCode() );
        result = 37 * result + ( getIntervalPrecision() == null ? 0 : this.getIntervalPrecision().hashCode() );
        result = 37 * result + ( getIntervalType() == null ? 0 : this.getIntervalType().hashCode() );
        result = 37 * result + ( getIsGenerated() == null ? 0 : this.getIsGenerated().hashCode() );
        result = 37 * result + ( getIsIdentity() == null ? 0 : this.getIsIdentity().hashCode() );
        result = 37 * result + ( getIsNullable() == null ? 0 : this.getIsNullable().hashCode() );
        result = 37 * result + ( getIsVisible() == null ? 0 : this.getIsVisible().hashCode() );
        result = 37 * result + ( getMaximumCardinality() == null ? 0 : this.getMaximumCardinality().hashCode() );
        result = 37 * result + ( getNumericPrecision() == null ? 0 : this.getNumericPrecision().hashCode() );
        result = 37 * result + ( getNumericPrecisionRadix() == null ? 0 : this.getNumericPrecisionRadix().hashCode() );
        result = 37 * result + ( getNumericScale() == null ? 0 : this.getNumericScale().hashCode() );
        result = 37 * result + ( getOrdinalPosition() == null ? 0 : this.getOrdinalPosition().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getSelectivity() == null ? 0 : this.getSelectivity().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


