// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Columns generated by hbm2java
 */
public class Columns  implements java.io.Serializable {


     private ColumnsId id;

    public Columns() {
    }

    public Columns(ColumnsId id) {
       this.id = id;
    }
   
    public ColumnsId getId() {
        return this.id;
    }
    
    public void setId(ColumnsId id) {
        this.id = id;
    }




}


