// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ColumnPrivileges generated by hbm2java
 */
public class ColumnPrivileges  implements java.io.Serializable {


     private ColumnPrivilegesId id;

    public ColumnPrivileges() {
    }

    public ColumnPrivileges(ColumnPrivilegesId id) {
       this.id = id;
    }
   
    public ColumnPrivilegesId getId() {
        return this.id;
    }
    
    public void setId(ColumnPrivilegesId id) {
        this.id = id;
    }




}


