// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Constants generated by hbm2java
 */
public class Constants  implements java.io.Serializable {


     private ConstantsId id;

    public Constants() {
    }

    public Constants(ConstantsId id) {
       this.id = id;
    }
   
    public ConstantsId getId() {
        return this.id;
    }
    
    public void setId(ConstantsId id) {
        this.id = id;
    }




}


