// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ConstraintColumnUsage generated by hbm2java
 */
public class ConstraintColumnUsage  implements java.io.Serializable {


     private ConstraintColumnUsageId id;

    public ConstraintColumnUsage() {
    }

    public ConstraintColumnUsage(ConstraintColumnUsageId id) {
       this.id = id;
    }
   
    public ConstraintColumnUsageId getId() {
        return this.id;
    }
    
    public void setId(ConstraintColumnUsageId id) {
        this.id = id;
    }




}


