// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ConstraintColumnUsageId generated by hbm2java
 */
public class ConstraintColumnUsageId  implements java.io.Serializable {


     private String columnName;
     private String constraintCatalog;
     private String constraintName;
     private String constraintSchema;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;

    public ConstraintColumnUsageId() {
    }

    public ConstraintColumnUsageId(String columnName, String constraintCatalog, String constraintName, String constraintSchema, String tableCatalog, String tableName, String tableSchema) {
       this.columnName = columnName;
       this.constraintCatalog = constraintCatalog;
       this.constraintName = constraintName;
       this.constraintSchema = constraintSchema;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }
    
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }
    public String getConstraintName() {
        return this.constraintName;
    }
    
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }
    public String getConstraintSchema() {
        return this.constraintSchema;
    }
    
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConstraintColumnUsageId) ) return false;
		 ConstraintColumnUsageId castOther = ( ConstraintColumnUsageId ) other; 
         
		 return ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) )
 && ( (this.getConstraintCatalog()==castOther.getConstraintCatalog()) || ( this.getConstraintCatalog()!=null && castOther.getConstraintCatalog()!=null && this.getConstraintCatalog().equals(castOther.getConstraintCatalog()) ) )
 && ( (this.getConstraintName()==castOther.getConstraintName()) || ( this.getConstraintName()!=null && castOther.getConstraintName()!=null && this.getConstraintName().equals(castOther.getConstraintName()) ) )
 && ( (this.getConstraintSchema()==castOther.getConstraintSchema()) || ( this.getConstraintSchema()!=null && castOther.getConstraintSchema()!=null && this.getConstraintSchema().equals(castOther.getConstraintSchema()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
        result = 37 * result + ( getConstraintCatalog() == null ? 0 : this.getConstraintCatalog().hashCode() );
        result = 37 * result + ( getConstraintName() == null ? 0 : this.getConstraintName().hashCode() );
        result = 37 * result + ( getConstraintSchema() == null ? 0 : this.getConstraintSchema().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


