// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private short countryId;
     private String country;
     private Timestamp lastUpdate;
     private Set cities = new HashSet(0);

    public Country() {
    }

	
    public Country(short countryId, String country, Timestamp lastUpdate) {
        this.countryId = countryId;
        this.country = country;
        this.lastUpdate = lastUpdate;
    }
    public Country(short countryId, String country, Timestamp lastUpdate, Set cities) {
       this.countryId = countryId;
       this.country = country;
       this.lastUpdate = lastUpdate;
       this.cities = cities;
    }
   
    public short getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(short countryId) {
        this.countryId = countryId;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }




}


