// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * DomainConstraints generated by hbm2java
 */
public class DomainConstraints  implements java.io.Serializable {


     private DomainConstraintsId id;

    public DomainConstraints() {
    }

    public DomainConstraints(DomainConstraintsId id) {
       this.id = id;
    }
   
    public DomainConstraintsId getId() {
        return this.id;
    }
    
    public void setId(DomainConstraintsId id) {
        this.id = id;
    }




}


