// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * DomainsId generated by hbm2java
 */
public class DomainsId  implements java.io.Serializable {


     private Long characterMaximumLength;
     private Long characterOctetLength;
     private String characterSetCatalog;
     private String characterSetName;
     private String characterSetSchema;
     private String collationCatalog;
     private String collationName;
     private String collationSchema;
     private String dataType;
     private Integer datetimePrecision;
     private String declaredDataType;
     private Integer declaredNumericPrecision;
     private Integer declaredNumericScale;
     private String domainCatalog;
     private String domainDefault;
     private String domainName;
     private String domainOnUpdate;
     private String domainSchema;
     private String dtdIdentifier;
     private Integer geometrySrid;
     private String geometryType;
     private Integer intervalPrecision;
     private String intervalType;
     private Integer maximumCardinality;
     private Integer numericPrecision;
     private Integer numericPrecisionRadix;
     private Integer numericScale;
     private String parentDomainCatalog;
     private String parentDomainName;
     private String parentDomainSchema;
     private String remarks;

    public DomainsId() {
    }

    public DomainsId(Long characterMaximumLength, Long characterOctetLength, String characterSetCatalog, String characterSetName, String characterSetSchema, String collationCatalog, String collationName, String collationSchema, String dataType, Integer datetimePrecision, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, String domainCatalog, String domainDefault, String domainName, String domainOnUpdate, String domainSchema, String dtdIdentifier, Integer geometrySrid, String geometryType, Integer intervalPrecision, String intervalType, Integer maximumCardinality, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, String parentDomainCatalog, String parentDomainName, String parentDomainSchema, String remarks) {
       this.characterMaximumLength = characterMaximumLength;
       this.characterOctetLength = characterOctetLength;
       this.characterSetCatalog = characterSetCatalog;
       this.characterSetName = characterSetName;
       this.characterSetSchema = characterSetSchema;
       this.collationCatalog = collationCatalog;
       this.collationName = collationName;
       this.collationSchema = collationSchema;
       this.dataType = dataType;
       this.datetimePrecision = datetimePrecision;
       this.declaredDataType = declaredDataType;
       this.declaredNumericPrecision = declaredNumericPrecision;
       this.declaredNumericScale = declaredNumericScale;
       this.domainCatalog = domainCatalog;
       this.domainDefault = domainDefault;
       this.domainName = domainName;
       this.domainOnUpdate = domainOnUpdate;
       this.domainSchema = domainSchema;
       this.dtdIdentifier = dtdIdentifier;
       this.geometrySrid = geometrySrid;
       this.geometryType = geometryType;
       this.intervalPrecision = intervalPrecision;
       this.intervalType = intervalType;
       this.maximumCardinality = maximumCardinality;
       this.numericPrecision = numericPrecision;
       this.numericPrecisionRadix = numericPrecisionRadix;
       this.numericScale = numericScale;
       this.parentDomainCatalog = parentDomainCatalog;
       this.parentDomainName = parentDomainName;
       this.parentDomainSchema = parentDomainSchema;
       this.remarks = remarks;
    }
   
    public Long getCharacterMaximumLength() {
        return this.characterMaximumLength;
    }
    
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }
    public Long getCharacterOctetLength() {
        return this.characterOctetLength;
    }
    
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }
    public String getCharacterSetCatalog() {
        return this.characterSetCatalog;
    }
    
    public void setCharacterSetCatalog(String characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }
    public String getCharacterSetName() {
        return this.characterSetName;
    }
    
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }
    public String getCharacterSetSchema() {
        return this.characterSetSchema;
    }
    
    public void setCharacterSetSchema(String characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }
    public String getCollationCatalog() {
        return this.collationCatalog;
    }
    
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }
    public String getCollationName() {
        return this.collationName;
    }
    
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }
    public String getCollationSchema() {
        return this.collationSchema;
    }
    
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public Integer getDatetimePrecision() {
        return this.datetimePrecision;
    }
    
    public void setDatetimePrecision(Integer datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }
    public String getDeclaredDataType() {
        return this.declaredDataType;
    }
    
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }
    public Integer getDeclaredNumericPrecision() {
        return this.declaredNumericPrecision;
    }
    
    public void setDeclaredNumericPrecision(Integer declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }
    public Integer getDeclaredNumericScale() {
        return this.declaredNumericScale;
    }
    
    public void setDeclaredNumericScale(Integer declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }
    public String getDomainCatalog() {
        return this.domainCatalog;
    }
    
    public void setDomainCatalog(String domainCatalog) {
        this.domainCatalog = domainCatalog;
    }
    public String getDomainDefault() {
        return this.domainDefault;
    }
    
    public void setDomainDefault(String domainDefault) {
        this.domainDefault = domainDefault;
    }
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    public String getDomainOnUpdate() {
        return this.domainOnUpdate;
    }
    
    public void setDomainOnUpdate(String domainOnUpdate) {
        this.domainOnUpdate = domainOnUpdate;
    }
    public String getDomainSchema() {
        return this.domainSchema;
    }
    
    public void setDomainSchema(String domainSchema) {
        this.domainSchema = domainSchema;
    }
    public String getDtdIdentifier() {
        return this.dtdIdentifier;
    }
    
    public void setDtdIdentifier(String dtdIdentifier) {
        this.dtdIdentifier = dtdIdentifier;
    }
    public Integer getGeometrySrid() {
        return this.geometrySrid;
    }
    
    public void setGeometrySrid(Integer geometrySrid) {
        this.geometrySrid = geometrySrid;
    }
    public String getGeometryType() {
        return this.geometryType;
    }
    
    public void setGeometryType(String geometryType) {
        this.geometryType = geometryType;
    }
    public Integer getIntervalPrecision() {
        return this.intervalPrecision;
    }
    
    public void setIntervalPrecision(Integer intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }
    public String getIntervalType() {
        return this.intervalType;
    }
    
    public void setIntervalType(String intervalType) {
        this.intervalType = intervalType;
    }
    public Integer getMaximumCardinality() {
        return this.maximumCardinality;
    }
    
    public void setMaximumCardinality(Integer maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }
    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }
    
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }
    public Integer getNumericPrecisionRadix() {
        return this.numericPrecisionRadix;
    }
    
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }
    public Integer getNumericScale() {
        return this.numericScale;
    }
    
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }
    public String getParentDomainCatalog() {
        return this.parentDomainCatalog;
    }
    
    public void setParentDomainCatalog(String parentDomainCatalog) {
        this.parentDomainCatalog = parentDomainCatalog;
    }
    public String getParentDomainName() {
        return this.parentDomainName;
    }
    
    public void setParentDomainName(String parentDomainName) {
        this.parentDomainName = parentDomainName;
    }
    public String getParentDomainSchema() {
        return this.parentDomainSchema;
    }
    
    public void setParentDomainSchema(String parentDomainSchema) {
        this.parentDomainSchema = parentDomainSchema;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DomainsId) ) return false;
		 DomainsId castOther = ( DomainsId ) other; 
         
		 return ( (this.getCharacterMaximumLength()==castOther.getCharacterMaximumLength()) || ( this.getCharacterMaximumLength()!=null && castOther.getCharacterMaximumLength()!=null && this.getCharacterMaximumLength().equals(castOther.getCharacterMaximumLength()) ) )
 && ( (this.getCharacterOctetLength()==castOther.getCharacterOctetLength()) || ( this.getCharacterOctetLength()!=null && castOther.getCharacterOctetLength()!=null && this.getCharacterOctetLength().equals(castOther.getCharacterOctetLength()) ) )
 && ( (this.getCharacterSetCatalog()==castOther.getCharacterSetCatalog()) || ( this.getCharacterSetCatalog()!=null && castOther.getCharacterSetCatalog()!=null && this.getCharacterSetCatalog().equals(castOther.getCharacterSetCatalog()) ) )
 && ( (this.getCharacterSetName()==castOther.getCharacterSetName()) || ( this.getCharacterSetName()!=null && castOther.getCharacterSetName()!=null && this.getCharacterSetName().equals(castOther.getCharacterSetName()) ) )
 && ( (this.getCharacterSetSchema()==castOther.getCharacterSetSchema()) || ( this.getCharacterSetSchema()!=null && castOther.getCharacterSetSchema()!=null && this.getCharacterSetSchema().equals(castOther.getCharacterSetSchema()) ) )
 && ( (this.getCollationCatalog()==castOther.getCollationCatalog()) || ( this.getCollationCatalog()!=null && castOther.getCollationCatalog()!=null && this.getCollationCatalog().equals(castOther.getCollationCatalog()) ) )
 && ( (this.getCollationName()==castOther.getCollationName()) || ( this.getCollationName()!=null && castOther.getCollationName()!=null && this.getCollationName().equals(castOther.getCollationName()) ) )
 && ( (this.getCollationSchema()==castOther.getCollationSchema()) || ( this.getCollationSchema()!=null && castOther.getCollationSchema()!=null && this.getCollationSchema().equals(castOther.getCollationSchema()) ) )
 && ( (this.getDataType()==castOther.getDataType()) || ( this.getDataType()!=null && castOther.getDataType()!=null && this.getDataType().equals(castOther.getDataType()) ) )
 && ( (this.getDatetimePrecision()==castOther.getDatetimePrecision()) || ( this.getDatetimePrecision()!=null && castOther.getDatetimePrecision()!=null && this.getDatetimePrecision().equals(castOther.getDatetimePrecision()) ) )
 && ( (this.getDeclaredDataType()==castOther.getDeclaredDataType()) || ( this.getDeclaredDataType()!=null && castOther.getDeclaredDataType()!=null && this.getDeclaredDataType().equals(castOther.getDeclaredDataType()) ) )
 && ( (this.getDeclaredNumericPrecision()==castOther.getDeclaredNumericPrecision()) || ( this.getDeclaredNumericPrecision()!=null && castOther.getDeclaredNumericPrecision()!=null && this.getDeclaredNumericPrecision().equals(castOther.getDeclaredNumericPrecision()) ) )
 && ( (this.getDeclaredNumericScale()==castOther.getDeclaredNumericScale()) || ( this.getDeclaredNumericScale()!=null && castOther.getDeclaredNumericScale()!=null && this.getDeclaredNumericScale().equals(castOther.getDeclaredNumericScale()) ) )
 && ( (this.getDomainCatalog()==castOther.getDomainCatalog()) || ( this.getDomainCatalog()!=null && castOther.getDomainCatalog()!=null && this.getDomainCatalog().equals(castOther.getDomainCatalog()) ) )
 && ( (this.getDomainDefault()==castOther.getDomainDefault()) || ( this.getDomainDefault()!=null && castOther.getDomainDefault()!=null && this.getDomainDefault().equals(castOther.getDomainDefault()) ) )
 && ( (this.getDomainName()==castOther.getDomainName()) || ( this.getDomainName()!=null && castOther.getDomainName()!=null && this.getDomainName().equals(castOther.getDomainName()) ) )
 && ( (this.getDomainOnUpdate()==castOther.getDomainOnUpdate()) || ( this.getDomainOnUpdate()!=null && castOther.getDomainOnUpdate()!=null && this.getDomainOnUpdate().equals(castOther.getDomainOnUpdate()) ) )
 && ( (this.getDomainSchema()==castOther.getDomainSchema()) || ( this.getDomainSchema()!=null && castOther.getDomainSchema()!=null && this.getDomainSchema().equals(castOther.getDomainSchema()) ) )
 && ( (this.getDtdIdentifier()==castOther.getDtdIdentifier()) || ( this.getDtdIdentifier()!=null && castOther.getDtdIdentifier()!=null && this.getDtdIdentifier().equals(castOther.getDtdIdentifier()) ) )
 && ( (this.getGeometrySrid()==castOther.getGeometrySrid()) || ( this.getGeometrySrid()!=null && castOther.getGeometrySrid()!=null && this.getGeometrySrid().equals(castOther.getGeometrySrid()) ) )
 && ( (this.getGeometryType()==castOther.getGeometryType()) || ( this.getGeometryType()!=null && castOther.getGeometryType()!=null && this.getGeometryType().equals(castOther.getGeometryType()) ) )
 && ( (this.getIntervalPrecision()==castOther.getIntervalPrecision()) || ( this.getIntervalPrecision()!=null && castOther.getIntervalPrecision()!=null && this.getIntervalPrecision().equals(castOther.getIntervalPrecision()) ) )
 && ( (this.getIntervalType()==castOther.getIntervalType()) || ( this.getIntervalType()!=null && castOther.getIntervalType()!=null && this.getIntervalType().equals(castOther.getIntervalType()) ) )
 && ( (this.getMaximumCardinality()==castOther.getMaximumCardinality()) || ( this.getMaximumCardinality()!=null && castOther.getMaximumCardinality()!=null && this.getMaximumCardinality().equals(castOther.getMaximumCardinality()) ) )
 && ( (this.getNumericPrecision()==castOther.getNumericPrecision()) || ( this.getNumericPrecision()!=null && castOther.getNumericPrecision()!=null && this.getNumericPrecision().equals(castOther.getNumericPrecision()) ) )
 && ( (this.getNumericPrecisionRadix()==castOther.getNumericPrecisionRadix()) || ( this.getNumericPrecisionRadix()!=null && castOther.getNumericPrecisionRadix()!=null && this.getNumericPrecisionRadix().equals(castOther.getNumericPrecisionRadix()) ) )
 && ( (this.getNumericScale()==castOther.getNumericScale()) || ( this.getNumericScale()!=null && castOther.getNumericScale()!=null && this.getNumericScale().equals(castOther.getNumericScale()) ) )
 && ( (this.getParentDomainCatalog()==castOther.getParentDomainCatalog()) || ( this.getParentDomainCatalog()!=null && castOther.getParentDomainCatalog()!=null && this.getParentDomainCatalog().equals(castOther.getParentDomainCatalog()) ) )
 && ( (this.getParentDomainName()==castOther.getParentDomainName()) || ( this.getParentDomainName()!=null && castOther.getParentDomainName()!=null && this.getParentDomainName().equals(castOther.getParentDomainName()) ) )
 && ( (this.getParentDomainSchema()==castOther.getParentDomainSchema()) || ( this.getParentDomainSchema()!=null && castOther.getParentDomainSchema()!=null && this.getParentDomainSchema().equals(castOther.getParentDomainSchema()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCharacterMaximumLength() == null ? 0 : this.getCharacterMaximumLength().hashCode() );
        result = 37 * result + ( getCharacterOctetLength() == null ? 0 : this.getCharacterOctetLength().hashCode() );
        result = 37 * result + ( getCharacterSetCatalog() == null ? 0 : this.getCharacterSetCatalog().hashCode() );
        result = 37 * result + ( getCharacterSetName() == null ? 0 : this.getCharacterSetName().hashCode() );
        result = 37 * result + ( getCharacterSetSchema() == null ? 0 : this.getCharacterSetSchema().hashCode() );
        result = 37 * result + ( getCollationCatalog() == null ? 0 : this.getCollationCatalog().hashCode() );
        result = 37 * result + ( getCollationName() == null ? 0 : this.getCollationName().hashCode() );
        result = 37 * result + ( getCollationSchema() == null ? 0 : this.getCollationSchema().hashCode() );
        result = 37 * result + ( getDataType() == null ? 0 : this.getDataType().hashCode() );
        result = 37 * result + ( getDatetimePrecision() == null ? 0 : this.getDatetimePrecision().hashCode() );
        result = 37 * result + ( getDeclaredDataType() == null ? 0 : this.getDeclaredDataType().hashCode() );
        result = 37 * result + ( getDeclaredNumericPrecision() == null ? 0 : this.getDeclaredNumericPrecision().hashCode() );
        result = 37 * result + ( getDeclaredNumericScale() == null ? 0 : this.getDeclaredNumericScale().hashCode() );
        result = 37 * result + ( getDomainCatalog() == null ? 0 : this.getDomainCatalog().hashCode() );
        result = 37 * result + ( getDomainDefault() == null ? 0 : this.getDomainDefault().hashCode() );
        result = 37 * result + ( getDomainName() == null ? 0 : this.getDomainName().hashCode() );
        result = 37 * result + ( getDomainOnUpdate() == null ? 0 : this.getDomainOnUpdate().hashCode() );
        result = 37 * result + ( getDomainSchema() == null ? 0 : this.getDomainSchema().hashCode() );
        result = 37 * result + ( getDtdIdentifier() == null ? 0 : this.getDtdIdentifier().hashCode() );
        result = 37 * result + ( getGeometrySrid() == null ? 0 : this.getGeometrySrid().hashCode() );
        result = 37 * result + ( getGeometryType() == null ? 0 : this.getGeometryType().hashCode() );
        result = 37 * result + ( getIntervalPrecision() == null ? 0 : this.getIntervalPrecision().hashCode() );
        result = 37 * result + ( getIntervalType() == null ? 0 : this.getIntervalType().hashCode() );
        result = 37 * result + ( getMaximumCardinality() == null ? 0 : this.getMaximumCardinality().hashCode() );
        result = 37 * result + ( getNumericPrecision() == null ? 0 : this.getNumericPrecision().hashCode() );
        result = 37 * result + ( getNumericPrecisionRadix() == null ? 0 : this.getNumericPrecisionRadix().hashCode() );
        result = 37 * result + ( getNumericScale() == null ? 0 : this.getNumericScale().hashCode() );
        result = 37 * result + ( getParentDomainCatalog() == null ? 0 : this.getParentDomainCatalog().hashCode() );
        result = 37 * result + ( getParentDomainName() == null ? 0 : this.getParentDomainName().hashCode() );
        result = 37 * result + ( getParentDomainSchema() == null ? 0 : this.getParentDomainSchema().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         return result;
   }   


}


