// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Domains generated by hbm2java
 */
public class Domains  implements java.io.Serializable {


     private DomainsId id;

    public Domains() {
    }

    public Domains(DomainsId id) {
       this.id = id;
    }
   
    public DomainsId getId() {
        return this.id;
    }
    
    public void setId(DomainsId id) {
        this.id = id;
    }




}


