// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * DomainConstraintsId generated by hbm2java
 */
public class DomainConstraintsId  implements java.io.Serializable {


     private String constraintCatalog;
     private String constraintName;
     private String constraintSchema;
     private String domainCatalog;
     private String domainName;
     private String domainSchema;
     private String initiallyDeferred;
     private String isDeferrable;
     private String remarks;

    public DomainConstraintsId() {
    }

    public DomainConstraintsId(String constraintCatalog, String constraintName, String constraintSchema, String domainCatalog, String domainName, String domainSchema, String initiallyDeferred, String isDeferrable, String remarks) {
       this.constraintCatalog = constraintCatalog;
       this.constraintName = constraintName;
       this.constraintSchema = constraintSchema;
       this.domainCatalog = domainCatalog;
       this.domainName = domainName;
       this.domainSchema = domainSchema;
       this.initiallyDeferred = initiallyDeferred;
       this.isDeferrable = isDeferrable;
       this.remarks = remarks;
    }
   
    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }
    
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }
    public String getConstraintName() {
        return this.constraintName;
    }
    
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }
    public String getConstraintSchema() {
        return this.constraintSchema;
    }
    
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }
    public String getDomainCatalog() {
        return this.domainCatalog;
    }
    
    public void setDomainCatalog(String domainCatalog) {
        this.domainCatalog = domainCatalog;
    }
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    public String getDomainSchema() {
        return this.domainSchema;
    }
    
    public void setDomainSchema(String domainSchema) {
        this.domainSchema = domainSchema;
    }
    public String getInitiallyDeferred() {
        return this.initiallyDeferred;
    }
    
    public void setInitiallyDeferred(String initiallyDeferred) {
        this.initiallyDeferred = initiallyDeferred;
    }
    public String getIsDeferrable() {
        return this.isDeferrable;
    }
    
    public void setIsDeferrable(String isDeferrable) {
        this.isDeferrable = isDeferrable;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DomainConstraintsId) ) return false;
		 DomainConstraintsId castOther = ( DomainConstraintsId ) other; 
         
		 return ( (this.getConstraintCatalog()==castOther.getConstraintCatalog()) || ( this.getConstraintCatalog()!=null && castOther.getConstraintCatalog()!=null && this.getConstraintCatalog().equals(castOther.getConstraintCatalog()) ) )
 && ( (this.getConstraintName()==castOther.getConstraintName()) || ( this.getConstraintName()!=null && castOther.getConstraintName()!=null && this.getConstraintName().equals(castOther.getConstraintName()) ) )
 && ( (this.getConstraintSchema()==castOther.getConstraintSchema()) || ( this.getConstraintSchema()!=null && castOther.getConstraintSchema()!=null && this.getConstraintSchema().equals(castOther.getConstraintSchema()) ) )
 && ( (this.getDomainCatalog()==castOther.getDomainCatalog()) || ( this.getDomainCatalog()!=null && castOther.getDomainCatalog()!=null && this.getDomainCatalog().equals(castOther.getDomainCatalog()) ) )
 && ( (this.getDomainName()==castOther.getDomainName()) || ( this.getDomainName()!=null && castOther.getDomainName()!=null && this.getDomainName().equals(castOther.getDomainName()) ) )
 && ( (this.getDomainSchema()==castOther.getDomainSchema()) || ( this.getDomainSchema()!=null && castOther.getDomainSchema()!=null && this.getDomainSchema().equals(castOther.getDomainSchema()) ) )
 && ( (this.getInitiallyDeferred()==castOther.getInitiallyDeferred()) || ( this.getInitiallyDeferred()!=null && castOther.getInitiallyDeferred()!=null && this.getInitiallyDeferred().equals(castOther.getInitiallyDeferred()) ) )
 && ( (this.getIsDeferrable()==castOther.getIsDeferrable()) || ( this.getIsDeferrable()!=null && castOther.getIsDeferrable()!=null && this.getIsDeferrable().equals(castOther.getIsDeferrable()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getConstraintCatalog() == null ? 0 : this.getConstraintCatalog().hashCode() );
        result = 37 * result + ( getConstraintName() == null ? 0 : this.getConstraintName().hashCode() );
        result = 37 * result + ( getConstraintSchema() == null ? 0 : this.getConstraintSchema().hashCode() );
        result = 37 * result + ( getDomainCatalog() == null ? 0 : this.getDomainCatalog().hashCode() );
        result = 37 * result + ( getDomainName() == null ? 0 : this.getDomainName().hashCode() );
        result = 37 * result + ( getDomainSchema() == null ? 0 : this.getDomainSchema().hashCode() );
        result = 37 * result + ( getInitiallyDeferred() == null ? 0 : this.getInitiallyDeferred().hashCode() );
        result = 37 * result + ( getIsDeferrable() == null ? 0 : this.getIsDeferrable().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         return result;
   }   


}


