// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ElementTypes generated by hbm2java
 */
public class ElementTypes  implements java.io.Serializable {


     private ElementTypesId id;

    public ElementTypes() {
    }

    public ElementTypes(ElementTypesId id) {
       this.id = id;
    }
   
    public ElementTypesId getId() {
        return this.id;
    }
    
    public void setId(ElementTypesId id) {
        this.id = id;
    }




}


