// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * EnumValuesId generated by hbm2java
 */
public class EnumValuesId  implements java.io.Serializable {


     private String enumIdentifier;
     private String objectCatalog;
     private String objectName;
     private String objectSchema;
     private String objectType;
     private String valueName;
     private String valueOrdinal;

    public EnumValuesId() {
    }

    public EnumValuesId(String enumIdentifier, String objectCatalog, String objectName, String objectSchema, String objectType, String valueName, String valueOrdinal) {
       this.enumIdentifier = enumIdentifier;
       this.objectCatalog = objectCatalog;
       this.objectName = objectName;
       this.objectSchema = objectSchema;
       this.objectType = objectType;
       this.valueName = valueName;
       this.valueOrdinal = valueOrdinal;
    }
   
    public String getEnumIdentifier() {
        return this.enumIdentifier;
    }
    
    public void setEnumIdentifier(String enumIdentifier) {
        this.enumIdentifier = enumIdentifier;
    }
    public String getObjectCatalog() {
        return this.objectCatalog;
    }
    
    public void setObjectCatalog(String objectCatalog) {
        this.objectCatalog = objectCatalog;
    }
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }
    public String getObjectSchema() {
        return this.objectSchema;
    }
    
    public void setObjectSchema(String objectSchema) {
        this.objectSchema = objectSchema;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public String getValueName() {
        return this.valueName;
    }
    
    public void setValueName(String valueName) {
        this.valueName = valueName;
    }
    public String getValueOrdinal() {
        return this.valueOrdinal;
    }
    
    public void setValueOrdinal(String valueOrdinal) {
        this.valueOrdinal = valueOrdinal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnumValuesId) ) return false;
		 EnumValuesId castOther = ( EnumValuesId ) other; 
         
		 return ( (this.getEnumIdentifier()==castOther.getEnumIdentifier()) || ( this.getEnumIdentifier()!=null && castOther.getEnumIdentifier()!=null && this.getEnumIdentifier().equals(castOther.getEnumIdentifier()) ) )
 && ( (this.getObjectCatalog()==castOther.getObjectCatalog()) || ( this.getObjectCatalog()!=null && castOther.getObjectCatalog()!=null && this.getObjectCatalog().equals(castOther.getObjectCatalog()) ) )
 && ( (this.getObjectName()==castOther.getObjectName()) || ( this.getObjectName()!=null && castOther.getObjectName()!=null && this.getObjectName().equals(castOther.getObjectName()) ) )
 && ( (this.getObjectSchema()==castOther.getObjectSchema()) || ( this.getObjectSchema()!=null && castOther.getObjectSchema()!=null && this.getObjectSchema().equals(castOther.getObjectSchema()) ) )
 && ( (this.getObjectType()==castOther.getObjectType()) || ( this.getObjectType()!=null && castOther.getObjectType()!=null && this.getObjectType().equals(castOther.getObjectType()) ) )
 && ( (this.getValueName()==castOther.getValueName()) || ( this.getValueName()!=null && castOther.getValueName()!=null && this.getValueName().equals(castOther.getValueName()) ) )
 && ( (this.getValueOrdinal()==castOther.getValueOrdinal()) || ( this.getValueOrdinal()!=null && castOther.getValueOrdinal()!=null && this.getValueOrdinal().equals(castOther.getValueOrdinal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getEnumIdentifier() == null ? 0 : this.getEnumIdentifier().hashCode() );
        result = 37 * result + ( getObjectCatalog() == null ? 0 : this.getObjectCatalog().hashCode() );
        result = 37 * result + ( getObjectName() == null ? 0 : this.getObjectName().hashCode() );
        result = 37 * result + ( getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode() );
        result = 37 * result + ( getObjectType() == null ? 0 : this.getObjectType().hashCode() );
        result = 37 * result + ( getValueName() == null ? 0 : this.getValueName().hashCode() );
        result = 37 * result + ( getValueOrdinal() == null ? 0 : this.getValueOrdinal().hashCode() );
         return result;
   }   


}


