// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * EnumValues generated by hbm2java
 */
public class EnumValues  implements java.io.Serializable {


     private EnumValuesId id;

    public EnumValues() {
    }

    public EnumValues(EnumValuesId id) {
       this.id = id;
    }
   
    public EnumValuesId getId() {
        return this.id;
    }
    
    public void setId(EnumValuesId id) {
        this.id = id;
    }




}


