// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * FieldsId generated by hbm2java
 */
public class FieldsId  implements java.io.Serializable {


     private Long characterMaximumLength;
     private Long characterOctetLength;
     private String characterSetCatalog;
     private String characterSetName;
     private String characterSetSchema;
     private String collationCatalog;
     private String collationName;
     private String collationSchema;
     private String dataType;
     private Integer datetimePrecision;
     private String declaredDataType;
     private Integer declaredNumericPrecision;
     private Integer declaredNumericScale;
     private String dtdIdentifier;
     private String fieldName;
     private Integer geometrySrid;
     private String geometryType;
     private Integer intervalPrecision;
     private String intervalType;
     private Integer maximumCardinality;
     private Integer numericPrecision;
     private Integer numericPrecisionRadix;
     private Integer numericScale;
     private String objectCatalog;
     private String objectName;
     private String objectSchema;
     private String objectType;
     private Integer ordinalPosition;
     private String rowIdentifier;

    public FieldsId() {
    }

    public FieldsId(Long characterMaximumLength, Long characterOctetLength, String characterSetCatalog, String characterSetName, String characterSetSchema, String collationCatalog, String collationName, String collationSchema, String dataType, Integer datetimePrecision, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, String dtdIdentifier, String fieldName, Integer geometrySrid, String geometryType, Integer intervalPrecision, String intervalType, Integer maximumCardinality, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, String objectCatalog, String objectName, String objectSchema, String objectType, Integer ordinalPosition, String rowIdentifier) {
       this.characterMaximumLength = characterMaximumLength;
       this.characterOctetLength = characterOctetLength;
       this.characterSetCatalog = characterSetCatalog;
       this.characterSetName = characterSetName;
       this.characterSetSchema = characterSetSchema;
       this.collationCatalog = collationCatalog;
       this.collationName = collationName;
       this.collationSchema = collationSchema;
       this.dataType = dataType;
       this.datetimePrecision = datetimePrecision;
       this.declaredDataType = declaredDataType;
       this.declaredNumericPrecision = declaredNumericPrecision;
       this.declaredNumericScale = declaredNumericScale;
       this.dtdIdentifier = dtdIdentifier;
       this.fieldName = fieldName;
       this.geometrySrid = geometrySrid;
       this.geometryType = geometryType;
       this.intervalPrecision = intervalPrecision;
       this.intervalType = intervalType;
       this.maximumCardinality = maximumCardinality;
       this.numericPrecision = numericPrecision;
       this.numericPrecisionRadix = numericPrecisionRadix;
       this.numericScale = numericScale;
       this.objectCatalog = objectCatalog;
       this.objectName = objectName;
       this.objectSchema = objectSchema;
       this.objectType = objectType;
       this.ordinalPosition = ordinalPosition;
       this.rowIdentifier = rowIdentifier;
    }
   
    public Long getCharacterMaximumLength() {
        return this.characterMaximumLength;
    }
    
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }
    public Long getCharacterOctetLength() {
        return this.characterOctetLength;
    }
    
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }
    public String getCharacterSetCatalog() {
        return this.characterSetCatalog;
    }
    
    public void setCharacterSetCatalog(String characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }
    public String getCharacterSetName() {
        return this.characterSetName;
    }
    
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }
    public String getCharacterSetSchema() {
        return this.characterSetSchema;
    }
    
    public void setCharacterSetSchema(String characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }
    public String getCollationCatalog() {
        return this.collationCatalog;
    }
    
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }
    public String getCollationName() {
        return this.collationName;
    }
    
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }
    public String getCollationSchema() {
        return this.collationSchema;
    }
    
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public Integer getDatetimePrecision() {
        return this.datetimePrecision;
    }
    
    public void setDatetimePrecision(Integer datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }
    public String getDeclaredDataType() {
        return this.declaredDataType;
    }
    
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }
    public Integer getDeclaredNumericPrecision() {
        return this.declaredNumericPrecision;
    }
    
    public void setDeclaredNumericPrecision(Integer declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }
    public Integer getDeclaredNumericScale() {
        return this.declaredNumericScale;
    }
    
    public void setDeclaredNumericScale(Integer declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }
    public String getDtdIdentifier() {
        return this.dtdIdentifier;
    }
    
    public void setDtdIdentifier(String dtdIdentifier) {
        this.dtdIdentifier = dtdIdentifier;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    public Integer getGeometrySrid() {
        return this.geometrySrid;
    }
    
    public void setGeometrySrid(Integer geometrySrid) {
        this.geometrySrid = geometrySrid;
    }
    public String getGeometryType() {
        return this.geometryType;
    }
    
    public void setGeometryType(String geometryType) {
        this.geometryType = geometryType;
    }
    public Integer getIntervalPrecision() {
        return this.intervalPrecision;
    }
    
    public void setIntervalPrecision(Integer intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }
    public String getIntervalType() {
        return this.intervalType;
    }
    
    public void setIntervalType(String intervalType) {
        this.intervalType = intervalType;
    }
    public Integer getMaximumCardinality() {
        return this.maximumCardinality;
    }
    
    public void setMaximumCardinality(Integer maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }
    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }
    
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }
    public Integer getNumericPrecisionRadix() {
        return this.numericPrecisionRadix;
    }
    
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }
    public Integer getNumericScale() {
        return this.numericScale;
    }
    
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }
    public String getObjectCatalog() {
        return this.objectCatalog;
    }
    
    public void setObjectCatalog(String objectCatalog) {
        this.objectCatalog = objectCatalog;
    }
    public String getObjectName() {
        return this.objectName;
    }
    
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }
    public String getObjectSchema() {
        return this.objectSchema;
    }
    
    public void setObjectSchema(String objectSchema) {
        this.objectSchema = objectSchema;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public Integer getOrdinalPosition() {
        return this.ordinalPosition;
    }
    
    public void setOrdinalPosition(Integer ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }
    public String getRowIdentifier() {
        return this.rowIdentifier;
    }
    
    public void setRowIdentifier(String rowIdentifier) {
        this.rowIdentifier = rowIdentifier;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FieldsId) ) return false;
		 FieldsId castOther = ( FieldsId ) other; 
         
		 return ( (this.getCharacterMaximumLength()==castOther.getCharacterMaximumLength()) || ( this.getCharacterMaximumLength()!=null && castOther.getCharacterMaximumLength()!=null && this.getCharacterMaximumLength().equals(castOther.getCharacterMaximumLength()) ) )
 && ( (this.getCharacterOctetLength()==castOther.getCharacterOctetLength()) || ( this.getCharacterOctetLength()!=null && castOther.getCharacterOctetLength()!=null && this.getCharacterOctetLength().equals(castOther.getCharacterOctetLength()) ) )
 && ( (this.getCharacterSetCatalog()==castOther.getCharacterSetCatalog()) || ( this.getCharacterSetCatalog()!=null && castOther.getCharacterSetCatalog()!=null && this.getCharacterSetCatalog().equals(castOther.getCharacterSetCatalog()) ) )
 && ( (this.getCharacterSetName()==castOther.getCharacterSetName()) || ( this.getCharacterSetName()!=null && castOther.getCharacterSetName()!=null && this.getCharacterSetName().equals(castOther.getCharacterSetName()) ) )
 && ( (this.getCharacterSetSchema()==castOther.getCharacterSetSchema()) || ( this.getCharacterSetSchema()!=null && castOther.getCharacterSetSchema()!=null && this.getCharacterSetSchema().equals(castOther.getCharacterSetSchema()) ) )
 && ( (this.getCollationCatalog()==castOther.getCollationCatalog()) || ( this.getCollationCatalog()!=null && castOther.getCollationCatalog()!=null && this.getCollationCatalog().equals(castOther.getCollationCatalog()) ) )
 && ( (this.getCollationName()==castOther.getCollationName()) || ( this.getCollationName()!=null && castOther.getCollationName()!=null && this.getCollationName().equals(castOther.getCollationName()) ) )
 && ( (this.getCollationSchema()==castOther.getCollationSchema()) || ( this.getCollationSchema()!=null && castOther.getCollationSchema()!=null && this.getCollationSchema().equals(castOther.getCollationSchema()) ) )
 && ( (this.getDataType()==castOther.getDataType()) || ( this.getDataType()!=null && castOther.getDataType()!=null && this.getDataType().equals(castOther.getDataType()) ) )
 && ( (this.getDatetimePrecision()==castOther.getDatetimePrecision()) || ( this.getDatetimePrecision()!=null && castOther.getDatetimePrecision()!=null && this.getDatetimePrecision().equals(castOther.getDatetimePrecision()) ) )
 && ( (this.getDeclaredDataType()==castOther.getDeclaredDataType()) || ( this.getDeclaredDataType()!=null && castOther.getDeclaredDataType()!=null && this.getDeclaredDataType().equals(castOther.getDeclaredDataType()) ) )
 && ( (this.getDeclaredNumericPrecision()==castOther.getDeclaredNumericPrecision()) || ( this.getDeclaredNumericPrecision()!=null && castOther.getDeclaredNumericPrecision()!=null && this.getDeclaredNumericPrecision().equals(castOther.getDeclaredNumericPrecision()) ) )
 && ( (this.getDeclaredNumericScale()==castOther.getDeclaredNumericScale()) || ( this.getDeclaredNumericScale()!=null && castOther.getDeclaredNumericScale()!=null && this.getDeclaredNumericScale().equals(castOther.getDeclaredNumericScale()) ) )
 && ( (this.getDtdIdentifier()==castOther.getDtdIdentifier()) || ( this.getDtdIdentifier()!=null && castOther.getDtdIdentifier()!=null && this.getDtdIdentifier().equals(castOther.getDtdIdentifier()) ) )
 && ( (this.getFieldName()==castOther.getFieldName()) || ( this.getFieldName()!=null && castOther.getFieldName()!=null && this.getFieldName().equals(castOther.getFieldName()) ) )
 && ( (this.getGeometrySrid()==castOther.getGeometrySrid()) || ( this.getGeometrySrid()!=null && castOther.getGeometrySrid()!=null && this.getGeometrySrid().equals(castOther.getGeometrySrid()) ) )
 && ( (this.getGeometryType()==castOther.getGeometryType()) || ( this.getGeometryType()!=null && castOther.getGeometryType()!=null && this.getGeometryType().equals(castOther.getGeometryType()) ) )
 && ( (this.getIntervalPrecision()==castOther.getIntervalPrecision()) || ( this.getIntervalPrecision()!=null && castOther.getIntervalPrecision()!=null && this.getIntervalPrecision().equals(castOther.getIntervalPrecision()) ) )
 && ( (this.getIntervalType()==castOther.getIntervalType()) || ( this.getIntervalType()!=null && castOther.getIntervalType()!=null && this.getIntervalType().equals(castOther.getIntervalType()) ) )
 && ( (this.getMaximumCardinality()==castOther.getMaximumCardinality()) || ( this.getMaximumCardinality()!=null && castOther.getMaximumCardinality()!=null && this.getMaximumCardinality().equals(castOther.getMaximumCardinality()) ) )
 && ( (this.getNumericPrecision()==castOther.getNumericPrecision()) || ( this.getNumericPrecision()!=null && castOther.getNumericPrecision()!=null && this.getNumericPrecision().equals(castOther.getNumericPrecision()) ) )
 && ( (this.getNumericPrecisionRadix()==castOther.getNumericPrecisionRadix()) || ( this.getNumericPrecisionRadix()!=null && castOther.getNumericPrecisionRadix()!=null && this.getNumericPrecisionRadix().equals(castOther.getNumericPrecisionRadix()) ) )
 && ( (this.getNumericScale()==castOther.getNumericScale()) || ( this.getNumericScale()!=null && castOther.getNumericScale()!=null && this.getNumericScale().equals(castOther.getNumericScale()) ) )
 && ( (this.getObjectCatalog()==castOther.getObjectCatalog()) || ( this.getObjectCatalog()!=null && castOther.getObjectCatalog()!=null && this.getObjectCatalog().equals(castOther.getObjectCatalog()) ) )
 && ( (this.getObjectName()==castOther.getObjectName()) || ( this.getObjectName()!=null && castOther.getObjectName()!=null && this.getObjectName().equals(castOther.getObjectName()) ) )
 && ( (this.getObjectSchema()==castOther.getObjectSchema()) || ( this.getObjectSchema()!=null && castOther.getObjectSchema()!=null && this.getObjectSchema().equals(castOther.getObjectSchema()) ) )
 && ( (this.getObjectType()==castOther.getObjectType()) || ( this.getObjectType()!=null && castOther.getObjectType()!=null && this.getObjectType().equals(castOther.getObjectType()) ) )
 && ( (this.getOrdinalPosition()==castOther.getOrdinalPosition()) || ( this.getOrdinalPosition()!=null && castOther.getOrdinalPosition()!=null && this.getOrdinalPosition().equals(castOther.getOrdinalPosition()) ) )
 && ( (this.getRowIdentifier()==castOther.getRowIdentifier()) || ( this.getRowIdentifier()!=null && castOther.getRowIdentifier()!=null && this.getRowIdentifier().equals(castOther.getRowIdentifier()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCharacterMaximumLength() == null ? 0 : this.getCharacterMaximumLength().hashCode() );
        result = 37 * result + ( getCharacterOctetLength() == null ? 0 : this.getCharacterOctetLength().hashCode() );
        result = 37 * result + ( getCharacterSetCatalog() == null ? 0 : this.getCharacterSetCatalog().hashCode() );
        result = 37 * result + ( getCharacterSetName() == null ? 0 : this.getCharacterSetName().hashCode() );
        result = 37 * result + ( getCharacterSetSchema() == null ? 0 : this.getCharacterSetSchema().hashCode() );
        result = 37 * result + ( getCollationCatalog() == null ? 0 : this.getCollationCatalog().hashCode() );
        result = 37 * result + ( getCollationName() == null ? 0 : this.getCollationName().hashCode() );
        result = 37 * result + ( getCollationSchema() == null ? 0 : this.getCollationSchema().hashCode() );
        result = 37 * result + ( getDataType() == null ? 0 : this.getDataType().hashCode() );
        result = 37 * result + ( getDatetimePrecision() == null ? 0 : this.getDatetimePrecision().hashCode() );
        result = 37 * result + ( getDeclaredDataType() == null ? 0 : this.getDeclaredDataType().hashCode() );
        result = 37 * result + ( getDeclaredNumericPrecision() == null ? 0 : this.getDeclaredNumericPrecision().hashCode() );
        result = 37 * result + ( getDeclaredNumericScale() == null ? 0 : this.getDeclaredNumericScale().hashCode() );
        result = 37 * result + ( getDtdIdentifier() == null ? 0 : this.getDtdIdentifier().hashCode() );
        result = 37 * result + ( getFieldName() == null ? 0 : this.getFieldName().hashCode() );
        result = 37 * result + ( getGeometrySrid() == null ? 0 : this.getGeometrySrid().hashCode() );
        result = 37 * result + ( getGeometryType() == null ? 0 : this.getGeometryType().hashCode() );
        result = 37 * result + ( getIntervalPrecision() == null ? 0 : this.getIntervalPrecision().hashCode() );
        result = 37 * result + ( getIntervalType() == null ? 0 : this.getIntervalType().hashCode() );
        result = 37 * result + ( getMaximumCardinality() == null ? 0 : this.getMaximumCardinality().hashCode() );
        result = 37 * result + ( getNumericPrecision() == null ? 0 : this.getNumericPrecision().hashCode() );
        result = 37 * result + ( getNumericPrecisionRadix() == null ? 0 : this.getNumericPrecisionRadix().hashCode() );
        result = 37 * result + ( getNumericScale() == null ? 0 : this.getNumericScale().hashCode() );
        result = 37 * result + ( getObjectCatalog() == null ? 0 : this.getObjectCatalog().hashCode() );
        result = 37 * result + ( getObjectName() == null ? 0 : this.getObjectName().hashCode() );
        result = 37 * result + ( getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode() );
        result = 37 * result + ( getObjectType() == null ? 0 : this.getObjectType().hashCode() );
        result = 37 * result + ( getOrdinalPosition() == null ? 0 : this.getOrdinalPosition().hashCode() );
        result = 37 * result + ( getRowIdentifier() == null ? 0 : this.getRowIdentifier().hashCode() );
         return result;
   }   


}


