// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Fields generated by hbm2java
 */
public class Fields  implements java.io.Serializable {


     private FieldsId id;

    public Fields() {
    }

    public Fields(FieldsId id) {
       this.id = id;
    }
   
    public FieldsId getId() {
        return this.id;
    }
    
    public void setId(FieldsId id) {
        this.id = id;
    }




}


