// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Indexes generated by hbm2java
 */
public class Indexes  implements java.io.Serializable {


     private IndexesId id;

    public Indexes() {
    }

    public Indexes(IndexesId id) {
       this.id = id;
    }
   
    public IndexesId getId() {
        return this.id;
    }
    
    public void setId(IndexesId id) {
        this.id = id;
    }




}


