// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * IndexesId generated by hbm2java
 */
public class IndexesId  implements java.io.Serializable {


     private String indexCatalog;
     private String indexClass;
     private String indexName;
     private String indexSchema;
     private String indexTypeName;
     private Boolean isGenerated;
     private String nullsDistinct;
     private String remarks;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;

    public IndexesId() {
    }

    public IndexesId(String indexCatalog, String indexClass, String indexName, String indexSchema, String indexTypeName, Boolean isGenerated, String nullsDistinct, String remarks, String tableCatalog, String tableName, String tableSchema) {
       this.indexCatalog = indexCatalog;
       this.indexClass = indexClass;
       this.indexName = indexName;
       this.indexSchema = indexSchema;
       this.indexTypeName = indexTypeName;
       this.isGenerated = isGenerated;
       this.nullsDistinct = nullsDistinct;
       this.remarks = remarks;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getIndexCatalog() {
        return this.indexCatalog;
    }
    
    public void setIndexCatalog(String indexCatalog) {
        this.indexCatalog = indexCatalog;
    }
    public String getIndexClass() {
        return this.indexClass;
    }
    
    public void setIndexClass(String indexClass) {
        this.indexClass = indexClass;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    public String getIndexSchema() {
        return this.indexSchema;
    }
    
    public void setIndexSchema(String indexSchema) {
        this.indexSchema = indexSchema;
    }
    public String getIndexTypeName() {
        return this.indexTypeName;
    }
    
    public void setIndexTypeName(String indexTypeName) {
        this.indexTypeName = indexTypeName;
    }
    public Boolean getIsGenerated() {
        return this.isGenerated;
    }
    
    public void setIsGenerated(Boolean isGenerated) {
        this.isGenerated = isGenerated;
    }
    public String getNullsDistinct() {
        return this.nullsDistinct;
    }
    
    public void setNullsDistinct(String nullsDistinct) {
        this.nullsDistinct = nullsDistinct;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndexesId) ) return false;
		 IndexesId castOther = ( IndexesId ) other; 
         
		 return ( (this.getIndexCatalog()==castOther.getIndexCatalog()) || ( this.getIndexCatalog()!=null && castOther.getIndexCatalog()!=null && this.getIndexCatalog().equals(castOther.getIndexCatalog()) ) )
 && ( (this.getIndexClass()==castOther.getIndexClass()) || ( this.getIndexClass()!=null && castOther.getIndexClass()!=null && this.getIndexClass().equals(castOther.getIndexClass()) ) )
 && ( (this.getIndexName()==castOther.getIndexName()) || ( this.getIndexName()!=null && castOther.getIndexName()!=null && this.getIndexName().equals(castOther.getIndexName()) ) )
 && ( (this.getIndexSchema()==castOther.getIndexSchema()) || ( this.getIndexSchema()!=null && castOther.getIndexSchema()!=null && this.getIndexSchema().equals(castOther.getIndexSchema()) ) )
 && ( (this.getIndexTypeName()==castOther.getIndexTypeName()) || ( this.getIndexTypeName()!=null && castOther.getIndexTypeName()!=null && this.getIndexTypeName().equals(castOther.getIndexTypeName()) ) )
 && ( (this.getIsGenerated()==castOther.getIsGenerated()) || ( this.getIsGenerated()!=null && castOther.getIsGenerated()!=null && this.getIsGenerated().equals(castOther.getIsGenerated()) ) )
 && ( (this.getNullsDistinct()==castOther.getNullsDistinct()) || ( this.getNullsDistinct()!=null && castOther.getNullsDistinct()!=null && this.getNullsDistinct().equals(castOther.getNullsDistinct()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getIndexCatalog() == null ? 0 : this.getIndexCatalog().hashCode() );
        result = 37 * result + ( getIndexClass() == null ? 0 : this.getIndexClass().hashCode() );
        result = 37 * result + ( getIndexName() == null ? 0 : this.getIndexName().hashCode() );
        result = 37 * result + ( getIndexSchema() == null ? 0 : this.getIndexSchema().hashCode() );
        result = 37 * result + ( getIndexTypeName() == null ? 0 : this.getIndexTypeName().hashCode() );
        result = 37 * result + ( getIsGenerated() == null ? 0 : this.getIsGenerated().hashCode() );
        result = 37 * result + ( getNullsDistinct() == null ? 0 : this.getNullsDistinct().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


