// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * IndexColumnsId generated by hbm2java
 */
public class IndexColumnsId  implements java.io.Serializable {


     private String columnName;
     private String indexCatalog;
     private String indexName;
     private String indexSchema;
     private Boolean isUnique;
     private String nullOrdering;
     private String orderingSpecification;
     private Integer ordinalPosition;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;

    public IndexColumnsId() {
    }

    public IndexColumnsId(String columnName, String indexCatalog, String indexName, String indexSchema, Boolean isUnique, String nullOrdering, String orderingSpecification, Integer ordinalPosition, String tableCatalog, String tableName, String tableSchema) {
       this.columnName = columnName;
       this.indexCatalog = indexCatalog;
       this.indexName = indexName;
       this.indexSchema = indexSchema;
       this.isUnique = isUnique;
       this.nullOrdering = nullOrdering;
       this.orderingSpecification = orderingSpecification;
       this.ordinalPosition = ordinalPosition;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getIndexCatalog() {
        return this.indexCatalog;
    }
    
    public void setIndexCatalog(String indexCatalog) {
        this.indexCatalog = indexCatalog;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    public String getIndexSchema() {
        return this.indexSchema;
    }
    
    public void setIndexSchema(String indexSchema) {
        this.indexSchema = indexSchema;
    }
    public Boolean getIsUnique() {
        return this.isUnique;
    }
    
    public void setIsUnique(Boolean isUnique) {
        this.isUnique = isUnique;
    }
    public String getNullOrdering() {
        return this.nullOrdering;
    }
    
    public void setNullOrdering(String nullOrdering) {
        this.nullOrdering = nullOrdering;
    }
    public String getOrderingSpecification() {
        return this.orderingSpecification;
    }
    
    public void setOrderingSpecification(String orderingSpecification) {
        this.orderingSpecification = orderingSpecification;
    }
    public Integer getOrdinalPosition() {
        return this.ordinalPosition;
    }
    
    public void setOrdinalPosition(Integer ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndexColumnsId) ) return false;
		 IndexColumnsId castOther = ( IndexColumnsId ) other; 
         
		 return ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) )
 && ( (this.getIndexCatalog()==castOther.getIndexCatalog()) || ( this.getIndexCatalog()!=null && castOther.getIndexCatalog()!=null && this.getIndexCatalog().equals(castOther.getIndexCatalog()) ) )
 && ( (this.getIndexName()==castOther.getIndexName()) || ( this.getIndexName()!=null && castOther.getIndexName()!=null && this.getIndexName().equals(castOther.getIndexName()) ) )
 && ( (this.getIndexSchema()==castOther.getIndexSchema()) || ( this.getIndexSchema()!=null && castOther.getIndexSchema()!=null && this.getIndexSchema().equals(castOther.getIndexSchema()) ) )
 && ( (this.getIsUnique()==castOther.getIsUnique()) || ( this.getIsUnique()!=null && castOther.getIsUnique()!=null && this.getIsUnique().equals(castOther.getIsUnique()) ) )
 && ( (this.getNullOrdering()==castOther.getNullOrdering()) || ( this.getNullOrdering()!=null && castOther.getNullOrdering()!=null && this.getNullOrdering().equals(castOther.getNullOrdering()) ) )
 && ( (this.getOrderingSpecification()==castOther.getOrderingSpecification()) || ( this.getOrderingSpecification()!=null && castOther.getOrderingSpecification()!=null && this.getOrderingSpecification().equals(castOther.getOrderingSpecification()) ) )
 && ( (this.getOrdinalPosition()==castOther.getOrdinalPosition()) || ( this.getOrdinalPosition()!=null && castOther.getOrdinalPosition()!=null && this.getOrdinalPosition().equals(castOther.getOrdinalPosition()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
        result = 37 * result + ( getIndexCatalog() == null ? 0 : this.getIndexCatalog().hashCode() );
        result = 37 * result + ( getIndexName() == null ? 0 : this.getIndexName().hashCode() );
        result = 37 * result + ( getIndexSchema() == null ? 0 : this.getIndexSchema().hashCode() );
        result = 37 * result + ( getIsUnique() == null ? 0 : this.getIsUnique().hashCode() );
        result = 37 * result + ( getNullOrdering() == null ? 0 : this.getNullOrdering().hashCode() );
        result = 37 * result + ( getOrderingSpecification() == null ? 0 : this.getOrderingSpecification().hashCode() );
        result = 37 * result + ( getOrdinalPosition() == null ? 0 : this.getOrdinalPosition().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


