// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * InDoubt generated by hbm2java
 */
public class InDoubt  implements java.io.Serializable {


     private InDoubtId id;

    public InDoubt() {
    }

    public InDoubt(InDoubtId id) {
       this.id = id;
    }
   
    public InDoubtId getId() {
        return this.id;
    }
    
    public void setId(InDoubtId id) {
        this.id = id;
    }




}


