// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * InDoubtId generated by hbm2java
 */
public class InDoubtId  implements java.io.Serializable {


     private String transactionName;
     private String transactionState;

    public InDoubtId() {
    }

    public InDoubtId(String transactionName, String transactionState) {
       this.transactionName = transactionName;
       this.transactionState = transactionState;
    }
   
    public String getTransactionName() {
        return this.transactionName;
    }
    
    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }
    public String getTransactionState() {
        return this.transactionState;
    }
    
    public void setTransactionState(String transactionState) {
        this.transactionState = transactionState;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InDoubtId) ) return false;
		 InDoubtId castOther = ( InDoubtId ) other; 
         
		 return ( (this.getTransactionName()==castOther.getTransactionName()) || ( this.getTransactionName()!=null && castOther.getTransactionName()!=null && this.getTransactionName().equals(castOther.getTransactionName()) ) )
 && ( (this.getTransactionState()==castOther.getTransactionState()) || ( this.getTransactionState()!=null && castOther.getTransactionState()!=null && this.getTransactionState().equals(castOther.getTransactionState()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getTransactionName() == null ? 0 : this.getTransactionName().hashCode() );
        result = 37 * result + ( getTransactionState() == null ? 0 : this.getTransactionState().hashCode() );
         return result;
   }   


}


