// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * InformationSchemaCatalogName generated by hbm2java
 */
public class InformationSchemaCatalogName  implements java.io.Serializable {


     private String catalogName;

    public InformationSchemaCatalogName() {
    }

    public InformationSchemaCatalogName(String catalogName) {
       this.catalogName = catalogName;
    }
   
    public String getCatalogName() {
        return this.catalogName;
    }
    
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }




}


