// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private int inventoryId;
     private Film film;
     private Store store;
     private Timestamp lastUpdate;
     private Set rentals = new HashSet(0);

    public Inventory() {
    }

	
    public Inventory(int inventoryId, Film film, Store store, Timestamp lastUpdate) {
        this.inventoryId = inventoryId;
        this.film = film;
        this.store = store;
        this.lastUpdate = lastUpdate;
    }
    public Inventory(int inventoryId, Film film, Store store, Timestamp lastUpdate, Set rentals) {
       this.inventoryId = inventoryId;
       this.film = film;
       this.store = store;
       this.lastUpdate = lastUpdate;
       this.rentals = rentals;
    }
   
    public int getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(int inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Set rentals) {
        this.rentals = rentals;
    }




}


