// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * KeyColumnUsage generated by hbm2java
 */
public class KeyColumnUsage  implements java.io.Serializable {


     private KeyColumnUsageId id;

    public KeyColumnUsage() {
    }

    public KeyColumnUsage(KeyColumnUsageId id) {
       this.id = id;
    }
   
    public KeyColumnUsageId getId() {
        return this.id;
    }
    
    public void setId(KeyColumnUsageId id) {
        this.id = id;
    }




}


