// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private byte languageId;
     private String name;
     private Timestamp lastUpdate;
     private Set filmsForLanguageId = new HashSet(0);
     private Set filmsForOriginalLanguageId = new HashSet(0);

    public Language() {
    }

	
    public Language(byte languageId, String name, Timestamp lastUpdate) {
        this.languageId = languageId;
        this.name = name;
        this.lastUpdate = lastUpdate;
    }
    public Language(byte languageId, String name, Timestamp lastUpdate, Set filmsForLanguageId, Set filmsForOriginalLanguageId) {
       this.languageId = languageId;
       this.name = name;
       this.lastUpdate = lastUpdate;
       this.filmsForLanguageId = filmsForLanguageId;
       this.filmsForOriginalLanguageId = filmsForOriginalLanguageId;
    }
   
    public byte getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(byte languageId) {
        this.languageId = languageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getFilmsForLanguageId() {
        return this.filmsForLanguageId;
    }
    
    public void setFilmsForLanguageId(Set filmsForLanguageId) {
        this.filmsForLanguageId = filmsForLanguageId;
    }
    public Set getFilmsForOriginalLanguageId() {
        return this.filmsForOriginalLanguageId;
    }
    
    public void setFilmsForOriginalLanguageId(Set filmsForOriginalLanguageId) {
        this.filmsForOriginalLanguageId = filmsForOriginalLanguageId;
    }




}


