// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Locks generated by hbm2java
 */
public class Locks  implements java.io.Serializable {


     private LocksId id;

    public Locks() {
    }

    public Locks(LocksId id) {
       this.id = id;
    }
   
    public LocksId getId() {
        return this.id;
    }
    
    public void setId(LocksId id) {
        this.id = id;
    }




}


