// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * LocksId generated by hbm2java
 */
public class LocksId  implements java.io.Serializable {


     private String lockType;
     private Integer sessionId;
     private String tableName;
     private String tableSchema;

    public LocksId() {
    }

    public LocksId(String lockType, Integer sessionId, String tableName, String tableSchema) {
       this.lockType = lockType;
       this.sessionId = sessionId;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getLockType() {
        return this.lockType;
    }
    
    public void setLockType(String lockType) {
        this.lockType = lockType;
    }
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocksId) ) return false;
		 LocksId castOther = ( LocksId ) other; 
         
		 return ( (this.getLockType()==castOther.getLockType()) || ( this.getLockType()!=null && castOther.getLockType()!=null && this.getLockType().equals(castOther.getLockType()) ) )
 && ( (this.getSessionId()==castOther.getSessionId()) || ( this.getSessionId()!=null && castOther.getSessionId()!=null && this.getSessionId().equals(castOther.getSessionId()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getLockType() == null ? 0 : this.getLockType().hashCode() );
        result = 37 * result + ( getSessionId() == null ? 0 : this.getSessionId().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


