// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Parameters generated by hbm2java
 */
public class Parameters  implements java.io.Serializable {


     private ParametersId id;

    public Parameters() {
    }

    public Parameters(ParametersId id) {
       this.id = id;
    }
   
    public ParametersId getId() {
        return this.id;
    }
    
    public void setId(ParametersId id) {
        this.id = id;
    }




}


