// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ParametersId generated by hbm2java
 */
public class ParametersId  implements java.io.Serializable {


     private String asLocator;
     private Long characterMaximumLength;
     private Long characterOctetLength;
     private String characterSetCatalog;
     private String characterSetName;
     private String characterSetSchema;
     private String collationCatalog;
     private String collationName;
     private String collationSchema;
     private String dataType;
     private Integer datetimePrecision;
     private String declaredDataType;
     private Integer declaredNumericPrecision;
     private Integer declaredNumericScale;
     private String dtdIdentifier;
     private Integer geometrySrid;
     private String geometryType;
     private Integer intervalPrecision;
     private String intervalType;
     private String isResult;
     private Integer maximumCardinality;
     private Integer numericPrecision;
     private Integer numericPrecisionRadix;
     private Integer numericScale;
     private Integer ordinalPosition;
     private String parameterDefault;
     private String parameterMode;
     private String parameterName;
     private String specificCatalog;
     private String specificName;
     private String specificSchema;

    public ParametersId() {
    }

    public ParametersId(String asLocator, Long characterMaximumLength, Long characterOctetLength, String characterSetCatalog, String characterSetName, String characterSetSchema, String collationCatalog, String collationName, String collationSchema, String dataType, Integer datetimePrecision, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, String dtdIdentifier, Integer geometrySrid, String geometryType, Integer intervalPrecision, String intervalType, String isResult, Integer maximumCardinality, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, Integer ordinalPosition, String parameterDefault, String parameterMode, String parameterName, String specificCatalog, String specificName, String specificSchema) {
       this.asLocator = asLocator;
       this.characterMaximumLength = characterMaximumLength;
       this.characterOctetLength = characterOctetLength;
       this.characterSetCatalog = characterSetCatalog;
       this.characterSetName = characterSetName;
       this.characterSetSchema = characterSetSchema;
       this.collationCatalog = collationCatalog;
       this.collationName = collationName;
       this.collationSchema = collationSchema;
       this.dataType = dataType;
       this.datetimePrecision = datetimePrecision;
       this.declaredDataType = declaredDataType;
       this.declaredNumericPrecision = declaredNumericPrecision;
       this.declaredNumericScale = declaredNumericScale;
       this.dtdIdentifier = dtdIdentifier;
       this.geometrySrid = geometrySrid;
       this.geometryType = geometryType;
       this.intervalPrecision = intervalPrecision;
       this.intervalType = intervalType;
       this.isResult = isResult;
       this.maximumCardinality = maximumCardinality;
       this.numericPrecision = numericPrecision;
       this.numericPrecisionRadix = numericPrecisionRadix;
       this.numericScale = numericScale;
       this.ordinalPosition = ordinalPosition;
       this.parameterDefault = parameterDefault;
       this.parameterMode = parameterMode;
       this.parameterName = parameterName;
       this.specificCatalog = specificCatalog;
       this.specificName = specificName;
       this.specificSchema = specificSchema;
    }
   
    public String getAsLocator() {
        return this.asLocator;
    }
    
    public void setAsLocator(String asLocator) {
        this.asLocator = asLocator;
    }
    public Long getCharacterMaximumLength() {
        return this.characterMaximumLength;
    }
    
    public void setCharacterMaximumLength(Long characterMaximumLength) {
        this.characterMaximumLength = characterMaximumLength;
    }
    public Long getCharacterOctetLength() {
        return this.characterOctetLength;
    }
    
    public void setCharacterOctetLength(Long characterOctetLength) {
        this.characterOctetLength = characterOctetLength;
    }
    public String getCharacterSetCatalog() {
        return this.characterSetCatalog;
    }
    
    public void setCharacterSetCatalog(String characterSetCatalog) {
        this.characterSetCatalog = characterSetCatalog;
    }
    public String getCharacterSetName() {
        return this.characterSetName;
    }
    
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName;
    }
    public String getCharacterSetSchema() {
        return this.characterSetSchema;
    }
    
    public void setCharacterSetSchema(String characterSetSchema) {
        this.characterSetSchema = characterSetSchema;
    }
    public String getCollationCatalog() {
        return this.collationCatalog;
    }
    
    public void setCollationCatalog(String collationCatalog) {
        this.collationCatalog = collationCatalog;
    }
    public String getCollationName() {
        return this.collationName;
    }
    
    public void setCollationName(String collationName) {
        this.collationName = collationName;
    }
    public String getCollationSchema() {
        return this.collationSchema;
    }
    
    public void setCollationSchema(String collationSchema) {
        this.collationSchema = collationSchema;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public Integer getDatetimePrecision() {
        return this.datetimePrecision;
    }
    
    public void setDatetimePrecision(Integer datetimePrecision) {
        this.datetimePrecision = datetimePrecision;
    }
    public String getDeclaredDataType() {
        return this.declaredDataType;
    }
    
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }
    public Integer getDeclaredNumericPrecision() {
        return this.declaredNumericPrecision;
    }
    
    public void setDeclaredNumericPrecision(Integer declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }
    public Integer getDeclaredNumericScale() {
        return this.declaredNumericScale;
    }
    
    public void setDeclaredNumericScale(Integer declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }
    public String getDtdIdentifier() {
        return this.dtdIdentifier;
    }
    
    public void setDtdIdentifier(String dtdIdentifier) {
        this.dtdIdentifier = dtdIdentifier;
    }
    public Integer getGeometrySrid() {
        return this.geometrySrid;
    }
    
    public void setGeometrySrid(Integer geometrySrid) {
        this.geometrySrid = geometrySrid;
    }
    public String getGeometryType() {
        return this.geometryType;
    }
    
    public void setGeometryType(String geometryType) {
        this.geometryType = geometryType;
    }
    public Integer getIntervalPrecision() {
        return this.intervalPrecision;
    }
    
    public void setIntervalPrecision(Integer intervalPrecision) {
        this.intervalPrecision = intervalPrecision;
    }
    public String getIntervalType() {
        return this.intervalType;
    }
    
    public void setIntervalType(String intervalType) {
        this.intervalType = intervalType;
    }
    public String getIsResult() {
        return this.isResult;
    }
    
    public void setIsResult(String isResult) {
        this.isResult = isResult;
    }
    public Integer getMaximumCardinality() {
        return this.maximumCardinality;
    }
    
    public void setMaximumCardinality(Integer maximumCardinality) {
        this.maximumCardinality = maximumCardinality;
    }
    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }
    
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }
    public Integer getNumericPrecisionRadix() {
        return this.numericPrecisionRadix;
    }
    
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }
    public Integer getNumericScale() {
        return this.numericScale;
    }
    
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }
    public Integer getOrdinalPosition() {
        return this.ordinalPosition;
    }
    
    public void setOrdinalPosition(Integer ordinalPosition) {
        this.ordinalPosition = ordinalPosition;
    }
    public String getParameterDefault() {
        return this.parameterDefault;
    }
    
    public void setParameterDefault(String parameterDefault) {
        this.parameterDefault = parameterDefault;
    }
    public String getParameterMode() {
        return this.parameterMode;
    }
    
    public void setParameterMode(String parameterMode) {
        this.parameterMode = parameterMode;
    }
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
    public String getSpecificCatalog() {
        return this.specificCatalog;
    }
    
    public void setSpecificCatalog(String specificCatalog) {
        this.specificCatalog = specificCatalog;
    }
    public String getSpecificName() {
        return this.specificName;
    }
    
    public void setSpecificName(String specificName) {
        this.specificName = specificName;
    }
    public String getSpecificSchema() {
        return this.specificSchema;
    }
    
    public void setSpecificSchema(String specificSchema) {
        this.specificSchema = specificSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParametersId) ) return false;
		 ParametersId castOther = ( ParametersId ) other; 
         
		 return ( (this.getAsLocator()==castOther.getAsLocator()) || ( this.getAsLocator()!=null && castOther.getAsLocator()!=null && this.getAsLocator().equals(castOther.getAsLocator()) ) )
 && ( (this.getCharacterMaximumLength()==castOther.getCharacterMaximumLength()) || ( this.getCharacterMaximumLength()!=null && castOther.getCharacterMaximumLength()!=null && this.getCharacterMaximumLength().equals(castOther.getCharacterMaximumLength()) ) )
 && ( (this.getCharacterOctetLength()==castOther.getCharacterOctetLength()) || ( this.getCharacterOctetLength()!=null && castOther.getCharacterOctetLength()!=null && this.getCharacterOctetLength().equals(castOther.getCharacterOctetLength()) ) )
 && ( (this.getCharacterSetCatalog()==castOther.getCharacterSetCatalog()) || ( this.getCharacterSetCatalog()!=null && castOther.getCharacterSetCatalog()!=null && this.getCharacterSetCatalog().equals(castOther.getCharacterSetCatalog()) ) )
 && ( (this.getCharacterSetName()==castOther.getCharacterSetName()) || ( this.getCharacterSetName()!=null && castOther.getCharacterSetName()!=null && this.getCharacterSetName().equals(castOther.getCharacterSetName()) ) )
 && ( (this.getCharacterSetSchema()==castOther.getCharacterSetSchema()) || ( this.getCharacterSetSchema()!=null && castOther.getCharacterSetSchema()!=null && this.getCharacterSetSchema().equals(castOther.getCharacterSetSchema()) ) )
 && ( (this.getCollationCatalog()==castOther.getCollationCatalog()) || ( this.getCollationCatalog()!=null && castOther.getCollationCatalog()!=null && this.getCollationCatalog().equals(castOther.getCollationCatalog()) ) )
 && ( (this.getCollationName()==castOther.getCollationName()) || ( this.getCollationName()!=null && castOther.getCollationName()!=null && this.getCollationName().equals(castOther.getCollationName()) ) )
 && ( (this.getCollationSchema()==castOther.getCollationSchema()) || ( this.getCollationSchema()!=null && castOther.getCollationSchema()!=null && this.getCollationSchema().equals(castOther.getCollationSchema()) ) )
 && ( (this.getDataType()==castOther.getDataType()) || ( this.getDataType()!=null && castOther.getDataType()!=null && this.getDataType().equals(castOther.getDataType()) ) )
 && ( (this.getDatetimePrecision()==castOther.getDatetimePrecision()) || ( this.getDatetimePrecision()!=null && castOther.getDatetimePrecision()!=null && this.getDatetimePrecision().equals(castOther.getDatetimePrecision()) ) )
 && ( (this.getDeclaredDataType()==castOther.getDeclaredDataType()) || ( this.getDeclaredDataType()!=null && castOther.getDeclaredDataType()!=null && this.getDeclaredDataType().equals(castOther.getDeclaredDataType()) ) )
 && ( (this.getDeclaredNumericPrecision()==castOther.getDeclaredNumericPrecision()) || ( this.getDeclaredNumericPrecision()!=null && castOther.getDeclaredNumericPrecision()!=null && this.getDeclaredNumericPrecision().equals(castOther.getDeclaredNumericPrecision()) ) )
 && ( (this.getDeclaredNumericScale()==castOther.getDeclaredNumericScale()) || ( this.getDeclaredNumericScale()!=null && castOther.getDeclaredNumericScale()!=null && this.getDeclaredNumericScale().equals(castOther.getDeclaredNumericScale()) ) )
 && ( (this.getDtdIdentifier()==castOther.getDtdIdentifier()) || ( this.getDtdIdentifier()!=null && castOther.getDtdIdentifier()!=null && this.getDtdIdentifier().equals(castOther.getDtdIdentifier()) ) )
 && ( (this.getGeometrySrid()==castOther.getGeometrySrid()) || ( this.getGeometrySrid()!=null && castOther.getGeometrySrid()!=null && this.getGeometrySrid().equals(castOther.getGeometrySrid()) ) )
 && ( (this.getGeometryType()==castOther.getGeometryType()) || ( this.getGeometryType()!=null && castOther.getGeometryType()!=null && this.getGeometryType().equals(castOther.getGeometryType()) ) )
 && ( (this.getIntervalPrecision()==castOther.getIntervalPrecision()) || ( this.getIntervalPrecision()!=null && castOther.getIntervalPrecision()!=null && this.getIntervalPrecision().equals(castOther.getIntervalPrecision()) ) )
 && ( (this.getIntervalType()==castOther.getIntervalType()) || ( this.getIntervalType()!=null && castOther.getIntervalType()!=null && this.getIntervalType().equals(castOther.getIntervalType()) ) )
 && ( (this.getIsResult()==castOther.getIsResult()) || ( this.getIsResult()!=null && castOther.getIsResult()!=null && this.getIsResult().equals(castOther.getIsResult()) ) )
 && ( (this.getMaximumCardinality()==castOther.getMaximumCardinality()) || ( this.getMaximumCardinality()!=null && castOther.getMaximumCardinality()!=null && this.getMaximumCardinality().equals(castOther.getMaximumCardinality()) ) )
 && ( (this.getNumericPrecision()==castOther.getNumericPrecision()) || ( this.getNumericPrecision()!=null && castOther.getNumericPrecision()!=null && this.getNumericPrecision().equals(castOther.getNumericPrecision()) ) )
 && ( (this.getNumericPrecisionRadix()==castOther.getNumericPrecisionRadix()) || ( this.getNumericPrecisionRadix()!=null && castOther.getNumericPrecisionRadix()!=null && this.getNumericPrecisionRadix().equals(castOther.getNumericPrecisionRadix()) ) )
 && ( (this.getNumericScale()==castOther.getNumericScale()) || ( this.getNumericScale()!=null && castOther.getNumericScale()!=null && this.getNumericScale().equals(castOther.getNumericScale()) ) )
 && ( (this.getOrdinalPosition()==castOther.getOrdinalPosition()) || ( this.getOrdinalPosition()!=null && castOther.getOrdinalPosition()!=null && this.getOrdinalPosition().equals(castOther.getOrdinalPosition()) ) )
 && ( (this.getParameterDefault()==castOther.getParameterDefault()) || ( this.getParameterDefault()!=null && castOther.getParameterDefault()!=null && this.getParameterDefault().equals(castOther.getParameterDefault()) ) )
 && ( (this.getParameterMode()==castOther.getParameterMode()) || ( this.getParameterMode()!=null && castOther.getParameterMode()!=null && this.getParameterMode().equals(castOther.getParameterMode()) ) )
 && ( (this.getParameterName()==castOther.getParameterName()) || ( this.getParameterName()!=null && castOther.getParameterName()!=null && this.getParameterName().equals(castOther.getParameterName()) ) )
 && ( (this.getSpecificCatalog()==castOther.getSpecificCatalog()) || ( this.getSpecificCatalog()!=null && castOther.getSpecificCatalog()!=null && this.getSpecificCatalog().equals(castOther.getSpecificCatalog()) ) )
 && ( (this.getSpecificName()==castOther.getSpecificName()) || ( this.getSpecificName()!=null && castOther.getSpecificName()!=null && this.getSpecificName().equals(castOther.getSpecificName()) ) )
 && ( (this.getSpecificSchema()==castOther.getSpecificSchema()) || ( this.getSpecificSchema()!=null && castOther.getSpecificSchema()!=null && this.getSpecificSchema().equals(castOther.getSpecificSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAsLocator() == null ? 0 : this.getAsLocator().hashCode() );
        result = 37 * result + ( getCharacterMaximumLength() == null ? 0 : this.getCharacterMaximumLength().hashCode() );
        result = 37 * result + ( getCharacterOctetLength() == null ? 0 : this.getCharacterOctetLength().hashCode() );
        result = 37 * result + ( getCharacterSetCatalog() == null ? 0 : this.getCharacterSetCatalog().hashCode() );
        result = 37 * result + ( getCharacterSetName() == null ? 0 : this.getCharacterSetName().hashCode() );
        result = 37 * result + ( getCharacterSetSchema() == null ? 0 : this.getCharacterSetSchema().hashCode() );
        result = 37 * result + ( getCollationCatalog() == null ? 0 : this.getCollationCatalog().hashCode() );
        result = 37 * result + ( getCollationName() == null ? 0 : this.getCollationName().hashCode() );
        result = 37 * result + ( getCollationSchema() == null ? 0 : this.getCollationSchema().hashCode() );
        result = 37 * result + ( getDataType() == null ? 0 : this.getDataType().hashCode() );
        result = 37 * result + ( getDatetimePrecision() == null ? 0 : this.getDatetimePrecision().hashCode() );
        result = 37 * result + ( getDeclaredDataType() == null ? 0 : this.getDeclaredDataType().hashCode() );
        result = 37 * result + ( getDeclaredNumericPrecision() == null ? 0 : this.getDeclaredNumericPrecision().hashCode() );
        result = 37 * result + ( getDeclaredNumericScale() == null ? 0 : this.getDeclaredNumericScale().hashCode() );
        result = 37 * result + ( getDtdIdentifier() == null ? 0 : this.getDtdIdentifier().hashCode() );
        result = 37 * result + ( getGeometrySrid() == null ? 0 : this.getGeometrySrid().hashCode() );
        result = 37 * result + ( getGeometryType() == null ? 0 : this.getGeometryType().hashCode() );
        result = 37 * result + ( getIntervalPrecision() == null ? 0 : this.getIntervalPrecision().hashCode() );
        result = 37 * result + ( getIntervalType() == null ? 0 : this.getIntervalType().hashCode() );
        result = 37 * result + ( getIsResult() == null ? 0 : this.getIsResult().hashCode() );
        result = 37 * result + ( getMaximumCardinality() == null ? 0 : this.getMaximumCardinality().hashCode() );
        result = 37 * result + ( getNumericPrecision() == null ? 0 : this.getNumericPrecision().hashCode() );
        result = 37 * result + ( getNumericPrecisionRadix() == null ? 0 : this.getNumericPrecisionRadix().hashCode() );
        result = 37 * result + ( getNumericScale() == null ? 0 : this.getNumericScale().hashCode() );
        result = 37 * result + ( getOrdinalPosition() == null ? 0 : this.getOrdinalPosition().hashCode() );
        result = 37 * result + ( getParameterDefault() == null ? 0 : this.getParameterDefault().hashCode() );
        result = 37 * result + ( getParameterMode() == null ? 0 : this.getParameterMode().hashCode() );
        result = 37 * result + ( getParameterName() == null ? 0 : this.getParameterName().hashCode() );
        result = 37 * result + ( getSpecificCatalog() == null ? 0 : this.getSpecificCatalog().hashCode() );
        result = 37 * result + ( getSpecificName() == null ? 0 : this.getSpecificName().hashCode() );
        result = 37 * result + ( getSpecificSchema() == null ? 0 : this.getSpecificSchema().hashCode() );
         return result;
   }   


}


