// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private short paymentId;
     private Rental rental;
     private Staff staff;
     private Customer customer;
     private BigDecimal amount;
     private Timestamp paymentDate;
     private Timestamp lastUpdate;

    public Payment() {
    }

	
    public Payment(short paymentId, Staff staff, Customer customer, BigDecimal amount, Timestamp paymentDate, Timestamp lastUpdate) {
        this.paymentId = paymentId;
        this.staff = staff;
        this.customer = customer;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.lastUpdate = lastUpdate;
    }
    public Payment(short paymentId, Rental rental, Staff staff, Customer customer, BigDecimal amount, Timestamp paymentDate, Timestamp lastUpdate) {
       this.paymentId = paymentId;
       this.rental = rental;
       this.staff = staff;
       this.customer = customer;
       this.amount = amount;
       this.paymentDate = paymentDate;
       this.lastUpdate = lastUpdate;
    }
   
    public short getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(short paymentId) {
        this.paymentId = paymentId;
    }
    public Rental getRental() {
        return this.rental;
    }
    
    public void setRental(Rental rental) {
        this.rental = rental;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Timestamp getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Timestamp paymentDate) {
        this.paymentDate = paymentDate;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


