// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * QueryStatisticsId generated by hbm2java
 */
public class QueryStatisticsId  implements java.io.Serializable {


     private Double averageExecutionTime;
     private Double averageRowCount;
     private Double cumulativeExecutionTime;
     private Long cumulativeRowCount;
     private Integer executionCount;
     private Double maxExecutionTime;
     private Long maxRowCount;
     private Double minExecutionTime;
     private Long minRowCount;
     private String sqlStatement;
     private Double stdDevExecutionTime;
     private Double stdDevRowCount;

    public QueryStatisticsId() {
    }

    public QueryStatisticsId(Double averageExecutionTime, Double averageRowCount, Double cumulativeExecutionTime, Long cumulativeRowCount, Integer executionCount, Double maxExecutionTime, Long maxRowCount, Double minExecutionTime, Long minRowCount, String sqlStatement, Double stdDevExecutionTime, Double stdDevRowCount) {
       this.averageExecutionTime = averageExecutionTime;
       this.averageRowCount = averageRowCount;
       this.cumulativeExecutionTime = cumulativeExecutionTime;
       this.cumulativeRowCount = cumulativeRowCount;
       this.executionCount = executionCount;
       this.maxExecutionTime = maxExecutionTime;
       this.maxRowCount = maxRowCount;
       this.minExecutionTime = minExecutionTime;
       this.minRowCount = minRowCount;
       this.sqlStatement = sqlStatement;
       this.stdDevExecutionTime = stdDevExecutionTime;
       this.stdDevRowCount = stdDevRowCount;
    }
   
    public Double getAverageExecutionTime() {
        return this.averageExecutionTime;
    }
    
    public void setAverageExecutionTime(Double averageExecutionTime) {
        this.averageExecutionTime = averageExecutionTime;
    }
    public Double getAverageRowCount() {
        return this.averageRowCount;
    }
    
    public void setAverageRowCount(Double averageRowCount) {
        this.averageRowCount = averageRowCount;
    }
    public Double getCumulativeExecutionTime() {
        return this.cumulativeExecutionTime;
    }
    
    public void setCumulativeExecutionTime(Double cumulativeExecutionTime) {
        this.cumulativeExecutionTime = cumulativeExecutionTime;
    }
    public Long getCumulativeRowCount() {
        return this.cumulativeRowCount;
    }
    
    public void setCumulativeRowCount(Long cumulativeRowCount) {
        this.cumulativeRowCount = cumulativeRowCount;
    }
    public Integer getExecutionCount() {
        return this.executionCount;
    }
    
    public void setExecutionCount(Integer executionCount) {
        this.executionCount = executionCount;
    }
    public Double getMaxExecutionTime() {
        return this.maxExecutionTime;
    }
    
    public void setMaxExecutionTime(Double maxExecutionTime) {
        this.maxExecutionTime = maxExecutionTime;
    }
    public Long getMaxRowCount() {
        return this.maxRowCount;
    }
    
    public void setMaxRowCount(Long maxRowCount) {
        this.maxRowCount = maxRowCount;
    }
    public Double getMinExecutionTime() {
        return this.minExecutionTime;
    }
    
    public void setMinExecutionTime(Double minExecutionTime) {
        this.minExecutionTime = minExecutionTime;
    }
    public Long getMinRowCount() {
        return this.minRowCount;
    }
    
    public void setMinRowCount(Long minRowCount) {
        this.minRowCount = minRowCount;
    }
    public String getSqlStatement() {
        return this.sqlStatement;
    }
    
    public void setSqlStatement(String sqlStatement) {
        this.sqlStatement = sqlStatement;
    }
    public Double getStdDevExecutionTime() {
        return this.stdDevExecutionTime;
    }
    
    public void setStdDevExecutionTime(Double stdDevExecutionTime) {
        this.stdDevExecutionTime = stdDevExecutionTime;
    }
    public Double getStdDevRowCount() {
        return this.stdDevRowCount;
    }
    
    public void setStdDevRowCount(Double stdDevRowCount) {
        this.stdDevRowCount = stdDevRowCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QueryStatisticsId) ) return false;
		 QueryStatisticsId castOther = ( QueryStatisticsId ) other; 
         
		 return ( (this.getAverageExecutionTime()==castOther.getAverageExecutionTime()) || ( this.getAverageExecutionTime()!=null && castOther.getAverageExecutionTime()!=null && this.getAverageExecutionTime().equals(castOther.getAverageExecutionTime()) ) )
 && ( (this.getAverageRowCount()==castOther.getAverageRowCount()) || ( this.getAverageRowCount()!=null && castOther.getAverageRowCount()!=null && this.getAverageRowCount().equals(castOther.getAverageRowCount()) ) )
 && ( (this.getCumulativeExecutionTime()==castOther.getCumulativeExecutionTime()) || ( this.getCumulativeExecutionTime()!=null && castOther.getCumulativeExecutionTime()!=null && this.getCumulativeExecutionTime().equals(castOther.getCumulativeExecutionTime()) ) )
 && ( (this.getCumulativeRowCount()==castOther.getCumulativeRowCount()) || ( this.getCumulativeRowCount()!=null && castOther.getCumulativeRowCount()!=null && this.getCumulativeRowCount().equals(castOther.getCumulativeRowCount()) ) )
 && ( (this.getExecutionCount()==castOther.getExecutionCount()) || ( this.getExecutionCount()!=null && castOther.getExecutionCount()!=null && this.getExecutionCount().equals(castOther.getExecutionCount()) ) )
 && ( (this.getMaxExecutionTime()==castOther.getMaxExecutionTime()) || ( this.getMaxExecutionTime()!=null && castOther.getMaxExecutionTime()!=null && this.getMaxExecutionTime().equals(castOther.getMaxExecutionTime()) ) )
 && ( (this.getMaxRowCount()==castOther.getMaxRowCount()) || ( this.getMaxRowCount()!=null && castOther.getMaxRowCount()!=null && this.getMaxRowCount().equals(castOther.getMaxRowCount()) ) )
 && ( (this.getMinExecutionTime()==castOther.getMinExecutionTime()) || ( this.getMinExecutionTime()!=null && castOther.getMinExecutionTime()!=null && this.getMinExecutionTime().equals(castOther.getMinExecutionTime()) ) )
 && ( (this.getMinRowCount()==castOther.getMinRowCount()) || ( this.getMinRowCount()!=null && castOther.getMinRowCount()!=null && this.getMinRowCount().equals(castOther.getMinRowCount()) ) )
 && ( (this.getSqlStatement()==castOther.getSqlStatement()) || ( this.getSqlStatement()!=null && castOther.getSqlStatement()!=null && this.getSqlStatement().equals(castOther.getSqlStatement()) ) )
 && ( (this.getStdDevExecutionTime()==castOther.getStdDevExecutionTime()) || ( this.getStdDevExecutionTime()!=null && castOther.getStdDevExecutionTime()!=null && this.getStdDevExecutionTime().equals(castOther.getStdDevExecutionTime()) ) )
 && ( (this.getStdDevRowCount()==castOther.getStdDevRowCount()) || ( this.getStdDevRowCount()!=null && castOther.getStdDevRowCount()!=null && this.getStdDevRowCount().equals(castOther.getStdDevRowCount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAverageExecutionTime() == null ? 0 : this.getAverageExecutionTime().hashCode() );
        result = 37 * result + ( getAverageRowCount() == null ? 0 : this.getAverageRowCount().hashCode() );
        result = 37 * result + ( getCumulativeExecutionTime() == null ? 0 : this.getCumulativeExecutionTime().hashCode() );
        result = 37 * result + ( getCumulativeRowCount() == null ? 0 : this.getCumulativeRowCount().hashCode() );
        result = 37 * result + ( getExecutionCount() == null ? 0 : this.getExecutionCount().hashCode() );
        result = 37 * result + ( getMaxExecutionTime() == null ? 0 : this.getMaxExecutionTime().hashCode() );
        result = 37 * result + ( getMaxRowCount() == null ? 0 : this.getMaxRowCount().hashCode() );
        result = 37 * result + ( getMinExecutionTime() == null ? 0 : this.getMinExecutionTime().hashCode() );
        result = 37 * result + ( getMinRowCount() == null ? 0 : this.getMinRowCount().hashCode() );
        result = 37 * result + ( getSqlStatement() == null ? 0 : this.getSqlStatement().hashCode() );
        result = 37 * result + ( getStdDevExecutionTime() == null ? 0 : this.getStdDevExecutionTime().hashCode() );
        result = 37 * result + ( getStdDevRowCount() == null ? 0 : this.getStdDevRowCount().hashCode() );
         return result;
   }   


}


