// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ReferentialConstraintsId generated by hbm2java
 */
public class ReferentialConstraintsId  implements java.io.Serializable {


     private String constraintCatalog;
     private String constraintName;
     private String constraintSchema;
     private String deleteRule;
     private String matchOption;
     private String uniqueConstraintCatalog;
     private String uniqueConstraintName;
     private String uniqueConstraintSchema;
     private String updateRule;

    public ReferentialConstraintsId() {
    }

    public ReferentialConstraintsId(String constraintCatalog, String constraintName, String constraintSchema, String deleteRule, String matchOption, String uniqueConstraintCatalog, String uniqueConstraintName, String uniqueConstraintSchema, String updateRule) {
       this.constraintCatalog = constraintCatalog;
       this.constraintName = constraintName;
       this.constraintSchema = constraintSchema;
       this.deleteRule = deleteRule;
       this.matchOption = matchOption;
       this.uniqueConstraintCatalog = uniqueConstraintCatalog;
       this.uniqueConstraintName = uniqueConstraintName;
       this.uniqueConstraintSchema = uniqueConstraintSchema;
       this.updateRule = updateRule;
    }
   
    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }
    
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }
    public String getConstraintName() {
        return this.constraintName;
    }
    
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }
    public String getConstraintSchema() {
        return this.constraintSchema;
    }
    
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }
    public String getDeleteRule() {
        return this.deleteRule;
    }
    
    public void setDeleteRule(String deleteRule) {
        this.deleteRule = deleteRule;
    }
    public String getMatchOption() {
        return this.matchOption;
    }
    
    public void setMatchOption(String matchOption) {
        this.matchOption = matchOption;
    }
    public String getUniqueConstraintCatalog() {
        return this.uniqueConstraintCatalog;
    }
    
    public void setUniqueConstraintCatalog(String uniqueConstraintCatalog) {
        this.uniqueConstraintCatalog = uniqueConstraintCatalog;
    }
    public String getUniqueConstraintName() {
        return this.uniqueConstraintName;
    }
    
    public void setUniqueConstraintName(String uniqueConstraintName) {
        this.uniqueConstraintName = uniqueConstraintName;
    }
    public String getUniqueConstraintSchema() {
        return this.uniqueConstraintSchema;
    }
    
    public void setUniqueConstraintSchema(String uniqueConstraintSchema) {
        this.uniqueConstraintSchema = uniqueConstraintSchema;
    }
    public String getUpdateRule() {
        return this.updateRule;
    }
    
    public void setUpdateRule(String updateRule) {
        this.updateRule = updateRule;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReferentialConstraintsId) ) return false;
		 ReferentialConstraintsId castOther = ( ReferentialConstraintsId ) other; 
         
		 return ( (this.getConstraintCatalog()==castOther.getConstraintCatalog()) || ( this.getConstraintCatalog()!=null && castOther.getConstraintCatalog()!=null && this.getConstraintCatalog().equals(castOther.getConstraintCatalog()) ) )
 && ( (this.getConstraintName()==castOther.getConstraintName()) || ( this.getConstraintName()!=null && castOther.getConstraintName()!=null && this.getConstraintName().equals(castOther.getConstraintName()) ) )
 && ( (this.getConstraintSchema()==castOther.getConstraintSchema()) || ( this.getConstraintSchema()!=null && castOther.getConstraintSchema()!=null && this.getConstraintSchema().equals(castOther.getConstraintSchema()) ) )
 && ( (this.getDeleteRule()==castOther.getDeleteRule()) || ( this.getDeleteRule()!=null && castOther.getDeleteRule()!=null && this.getDeleteRule().equals(castOther.getDeleteRule()) ) )
 && ( (this.getMatchOption()==castOther.getMatchOption()) || ( this.getMatchOption()!=null && castOther.getMatchOption()!=null && this.getMatchOption().equals(castOther.getMatchOption()) ) )
 && ( (this.getUniqueConstraintCatalog()==castOther.getUniqueConstraintCatalog()) || ( this.getUniqueConstraintCatalog()!=null && castOther.getUniqueConstraintCatalog()!=null && this.getUniqueConstraintCatalog().equals(castOther.getUniqueConstraintCatalog()) ) )
 && ( (this.getUniqueConstraintName()==castOther.getUniqueConstraintName()) || ( this.getUniqueConstraintName()!=null && castOther.getUniqueConstraintName()!=null && this.getUniqueConstraintName().equals(castOther.getUniqueConstraintName()) ) )
 && ( (this.getUniqueConstraintSchema()==castOther.getUniqueConstraintSchema()) || ( this.getUniqueConstraintSchema()!=null && castOther.getUniqueConstraintSchema()!=null && this.getUniqueConstraintSchema().equals(castOther.getUniqueConstraintSchema()) ) )
 && ( (this.getUpdateRule()==castOther.getUpdateRule()) || ( this.getUpdateRule()!=null && castOther.getUpdateRule()!=null && this.getUpdateRule().equals(castOther.getUpdateRule()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getConstraintCatalog() == null ? 0 : this.getConstraintCatalog().hashCode() );
        result = 37 * result + ( getConstraintName() == null ? 0 : this.getConstraintName().hashCode() );
        result = 37 * result + ( getConstraintSchema() == null ? 0 : this.getConstraintSchema().hashCode() );
        result = 37 * result + ( getDeleteRule() == null ? 0 : this.getDeleteRule().hashCode() );
        result = 37 * result + ( getMatchOption() == null ? 0 : this.getMatchOption().hashCode() );
        result = 37 * result + ( getUniqueConstraintCatalog() == null ? 0 : this.getUniqueConstraintCatalog().hashCode() );
        result = 37 * result + ( getUniqueConstraintName() == null ? 0 : this.getUniqueConstraintName().hashCode() );
        result = 37 * result + ( getUniqueConstraintSchema() == null ? 0 : this.getUniqueConstraintSchema().hashCode() );
        result = 37 * result + ( getUpdateRule() == null ? 0 : this.getUpdateRule().hashCode() );
         return result;
   }   


}


