// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ReferentialConstraints generated by hbm2java
 */
public class ReferentialConstraints  implements java.io.Serializable {


     private ReferentialConstraintsId id;

    public ReferentialConstraints() {
    }

    public ReferentialConstraints(ReferentialConstraintsId id) {
       this.id = id;
    }
   
    public ReferentialConstraintsId getId() {
        return this.id;
    }
    
    public void setId(ReferentialConstraintsId id) {
        this.id = id;
    }




}


