// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Rental generated by hbm2java
 */
public class Rental  implements java.io.Serializable {


     private int rentalId;
     private Staff staff;
     private Inventory inventory;
     private Customer customer;
     private Timestamp rentalDate;
     private Timestamp returnDate;
     private Timestamp lastUpdate;
     private Set payments = new HashSet(0);

    public Rental() {
    }

	
    public Rental(int rentalId, Staff staff, Inventory inventory, Customer customer, Timestamp rentalDate, Timestamp lastUpdate) {
        this.rentalId = rentalId;
        this.staff = staff;
        this.inventory = inventory;
        this.customer = customer;
        this.rentalDate = rentalDate;
        this.lastUpdate = lastUpdate;
    }
    public Rental(int rentalId, Staff staff, Inventory inventory, Customer customer, Timestamp rentalDate, Timestamp returnDate, Timestamp lastUpdate, Set payments) {
       this.rentalId = rentalId;
       this.staff = staff;
       this.inventory = inventory;
       this.customer = customer;
       this.rentalDate = rentalDate;
       this.returnDate = returnDate;
       this.lastUpdate = lastUpdate;
       this.payments = payments;
    }
   
    public int getRentalId() {
        return this.rentalId;
    }
    
    public void setRentalId(int rentalId) {
        this.rentalId = rentalId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Timestamp getRentalDate() {
        return this.rentalDate;
    }
    
    public void setRentalDate(Timestamp rentalDate) {
        this.rentalDate = rentalDate;
    }
    public Timestamp getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Timestamp returnDate) {
        this.returnDate = returnDate;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


