// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Rights generated by hbm2java
 */
public class Rights  implements java.io.Serializable {


     private RightsId id;

    public Rights() {
    }

    public Rights(RightsId id) {
       this.id = id;
    }
   
    public RightsId getId() {
        return this.id;
    }
    
    public void setId(RightsId id) {
        this.id = id;
    }




}


