// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * RightsId generated by hbm2java
 */
public class RightsId  implements java.io.Serializable {


     private String grantedrole;
     private String grantee;
     private String granteetype;
     private String rights;
     private String tableName;
     private String tableSchema;

    public RightsId() {
    }

    public RightsId(String grantedrole, String grantee, String granteetype, String rights, String tableName, String tableSchema) {
       this.grantedrole = grantedrole;
       this.grantee = grantee;
       this.granteetype = granteetype;
       this.rights = rights;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getGrantedrole() {
        return this.grantedrole;
    }
    
    public void setGrantedrole(String grantedrole) {
        this.grantedrole = grantedrole;
    }
    public String getGrantee() {
        return this.grantee;
    }
    
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }
    public String getGranteetype() {
        return this.granteetype;
    }
    
    public void setGranteetype(String granteetype) {
        this.granteetype = granteetype;
    }
    public String getRights() {
        return this.rights;
    }
    
    public void setRights(String rights) {
        this.rights = rights;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RightsId) ) return false;
		 RightsId castOther = ( RightsId ) other; 
         
		 return ( (this.getGrantedrole()==castOther.getGrantedrole()) || ( this.getGrantedrole()!=null && castOther.getGrantedrole()!=null && this.getGrantedrole().equals(castOther.getGrantedrole()) ) )
 && ( (this.getGrantee()==castOther.getGrantee()) || ( this.getGrantee()!=null && castOther.getGrantee()!=null && this.getGrantee().equals(castOther.getGrantee()) ) )
 && ( (this.getGranteetype()==castOther.getGranteetype()) || ( this.getGranteetype()!=null && castOther.getGranteetype()!=null && this.getGranteetype().equals(castOther.getGranteetype()) ) )
 && ( (this.getRights()==castOther.getRights()) || ( this.getRights()!=null && castOther.getRights()!=null && this.getRights().equals(castOther.getRights()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getGrantedrole() == null ? 0 : this.getGrantedrole().hashCode() );
        result = 37 * result + ( getGrantee() == null ? 0 : this.getGrantee().hashCode() );
        result = 37 * result + ( getGranteetype() == null ? 0 : this.getGranteetype().hashCode() );
        result = 37 * result + ( getRights() == null ? 0 : this.getRights().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


