// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * RolesId generated by hbm2java
 */
public class RolesId  implements java.io.Serializable {


     private String remarks;
     private String roleName;

    public RolesId() {
    }

    public RolesId(String remarks, String roleName) {
       this.remarks = remarks;
       this.roleName = roleName;
    }
   
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesId) ) return false;
		 RolesId castOther = ( RolesId ) other; 
         
		 return ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getRoleName()==castOther.getRoleName()) || ( this.getRoleName()!=null && castOther.getRoleName()!=null && this.getRoleName().equals(castOther.getRoleName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getRoleName() == null ? 0 : this.getRoleName().hashCode() );
         return result;
   }   


}


