// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private RolesId id;

    public Roles() {
    }

    public Roles(RolesId id) {
       this.id = id;
    }
   
    public RolesId getId() {
        return this.id;
    }
    
    public void setId(RolesId id) {
        this.id = id;
    }




}


