// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Routines generated by hbm2java
 */
public class Routines  implements java.io.Serializable {


     private RoutinesId id;

    public Routines() {
    }

    public Routines(RoutinesId id) {
       this.id = id;
    }
   
    public RoutinesId getId() {
        return this.id;
    }
    
    public void setId(RoutinesId id) {
        this.id = id;
    }




}


