// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SchemataId generated by hbm2java
 */
public class SchemataId  implements java.io.Serializable {


     private String catalogName;
     private String defaultCharacterSetCatalog;
     private String defaultCharacterSetName;
     private String defaultCharacterSetSchema;
     private String defaultCollationName;
     private String remarks;
     private String schemaName;
     private String schemaOwner;
     private String sqlPath;

    public SchemataId() {
    }

    public SchemataId(String catalogName, String defaultCharacterSetCatalog, String defaultCharacterSetName, String defaultCharacterSetSchema, String defaultCollationName, String remarks, String schemaName, String schemaOwner, String sqlPath) {
       this.catalogName = catalogName;
       this.defaultCharacterSetCatalog = defaultCharacterSetCatalog;
       this.defaultCharacterSetName = defaultCharacterSetName;
       this.defaultCharacterSetSchema = defaultCharacterSetSchema;
       this.defaultCollationName = defaultCollationName;
       this.remarks = remarks;
       this.schemaName = schemaName;
       this.schemaOwner = schemaOwner;
       this.sqlPath = sqlPath;
    }
   
    public String getCatalogName() {
        return this.catalogName;
    }
    
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }
    public String getDefaultCharacterSetCatalog() {
        return this.defaultCharacterSetCatalog;
    }
    
    public void setDefaultCharacterSetCatalog(String defaultCharacterSetCatalog) {
        this.defaultCharacterSetCatalog = defaultCharacterSetCatalog;
    }
    public String getDefaultCharacterSetName() {
        return this.defaultCharacterSetName;
    }
    
    public void setDefaultCharacterSetName(String defaultCharacterSetName) {
        this.defaultCharacterSetName = defaultCharacterSetName;
    }
    public String getDefaultCharacterSetSchema() {
        return this.defaultCharacterSetSchema;
    }
    
    public void setDefaultCharacterSetSchema(String defaultCharacterSetSchema) {
        this.defaultCharacterSetSchema = defaultCharacterSetSchema;
    }
    public String getDefaultCollationName() {
        return this.defaultCollationName;
    }
    
    public void setDefaultCollationName(String defaultCollationName) {
        this.defaultCollationName = defaultCollationName;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getSchemaName() {
        return this.schemaName;
    }
    
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }
    public String getSchemaOwner() {
        return this.schemaOwner;
    }
    
    public void setSchemaOwner(String schemaOwner) {
        this.schemaOwner = schemaOwner;
    }
    public String getSqlPath() {
        return this.sqlPath;
    }
    
    public void setSqlPath(String sqlPath) {
        this.sqlPath = sqlPath;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SchemataId) ) return false;
		 SchemataId castOther = ( SchemataId ) other; 
         
		 return ( (this.getCatalogName()==castOther.getCatalogName()) || ( this.getCatalogName()!=null && castOther.getCatalogName()!=null && this.getCatalogName().equals(castOther.getCatalogName()) ) )
 && ( (this.getDefaultCharacterSetCatalog()==castOther.getDefaultCharacterSetCatalog()) || ( this.getDefaultCharacterSetCatalog()!=null && castOther.getDefaultCharacterSetCatalog()!=null && this.getDefaultCharacterSetCatalog().equals(castOther.getDefaultCharacterSetCatalog()) ) )
 && ( (this.getDefaultCharacterSetName()==castOther.getDefaultCharacterSetName()) || ( this.getDefaultCharacterSetName()!=null && castOther.getDefaultCharacterSetName()!=null && this.getDefaultCharacterSetName().equals(castOther.getDefaultCharacterSetName()) ) )
 && ( (this.getDefaultCharacterSetSchema()==castOther.getDefaultCharacterSetSchema()) || ( this.getDefaultCharacterSetSchema()!=null && castOther.getDefaultCharacterSetSchema()!=null && this.getDefaultCharacterSetSchema().equals(castOther.getDefaultCharacterSetSchema()) ) )
 && ( (this.getDefaultCollationName()==castOther.getDefaultCollationName()) || ( this.getDefaultCollationName()!=null && castOther.getDefaultCollationName()!=null && this.getDefaultCollationName().equals(castOther.getDefaultCollationName()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getSchemaName()==castOther.getSchemaName()) || ( this.getSchemaName()!=null && castOther.getSchemaName()!=null && this.getSchemaName().equals(castOther.getSchemaName()) ) )
 && ( (this.getSchemaOwner()==castOther.getSchemaOwner()) || ( this.getSchemaOwner()!=null && castOther.getSchemaOwner()!=null && this.getSchemaOwner().equals(castOther.getSchemaOwner()) ) )
 && ( (this.getSqlPath()==castOther.getSqlPath()) || ( this.getSqlPath()!=null && castOther.getSqlPath()!=null && this.getSqlPath().equals(castOther.getSqlPath()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCatalogName() == null ? 0 : this.getCatalogName().hashCode() );
        result = 37 * result + ( getDefaultCharacterSetCatalog() == null ? 0 : this.getDefaultCharacterSetCatalog().hashCode() );
        result = 37 * result + ( getDefaultCharacterSetName() == null ? 0 : this.getDefaultCharacterSetName().hashCode() );
        result = 37 * result + ( getDefaultCharacterSetSchema() == null ? 0 : this.getDefaultCharacterSetSchema().hashCode() );
        result = 37 * result + ( getDefaultCollationName() == null ? 0 : this.getDefaultCollationName().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getSchemaName() == null ? 0 : this.getSchemaName().hashCode() );
        result = 37 * result + ( getSchemaOwner() == null ? 0 : this.getSchemaOwner().hashCode() );
        result = 37 * result + ( getSqlPath() == null ? 0 : this.getSqlPath().hashCode() );
         return result;
   }   


}


