// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Schemata generated by hbm2java
 */
public class Schemata  implements java.io.Serializable {


     private SchemataId id;

    public Schemata() {
    }

    public Schemata(SchemataId id) {
       this.id = id;
    }
   
    public SchemataId getId() {
        return this.id;
    }
    
    public void setId(SchemataId id) {
        this.id = id;
    }




}


