// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Sequences generated by hbm2java
 */
public class Sequences  implements java.io.Serializable {


     private SequencesId id;

    public Sequences() {
    }

    public Sequences(SequencesId id) {
       this.id = id;
    }
   
    public SequencesId getId() {
        return this.id;
    }
    
    public void setId(SequencesId id) {
        this.id = id;
    }




}


