// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SequencesId generated by hbm2java
 */
public class SequencesId  implements java.io.Serializable {


     private Long baseValue;
     private Long cache;
     private String cycleOption;
     private String dataType;
     private String declaredDataType;
     private Integer declaredNumericPrecision;
     private Integer declaredNumericScale;
     private Long increment;
     private Long maximumValue;
     private Long minimumValue;
     private Integer numericPrecision;
     private Integer numericPrecisionRadix;
     private Integer numericScale;
     private String remarks;
     private String sequenceCatalog;
     private String sequenceName;
     private String sequenceSchema;
     private Long startValue;

    public SequencesId() {
    }

    public SequencesId(Long baseValue, Long cache, String cycleOption, String dataType, String declaredDataType, Integer declaredNumericPrecision, Integer declaredNumericScale, Long increment, Long maximumValue, Long minimumValue, Integer numericPrecision, Integer numericPrecisionRadix, Integer numericScale, String remarks, String sequenceCatalog, String sequenceName, String sequenceSchema, Long startValue) {
       this.baseValue = baseValue;
       this.cache = cache;
       this.cycleOption = cycleOption;
       this.dataType = dataType;
       this.declaredDataType = declaredDataType;
       this.declaredNumericPrecision = declaredNumericPrecision;
       this.declaredNumericScale = declaredNumericScale;
       this.increment = increment;
       this.maximumValue = maximumValue;
       this.minimumValue = minimumValue;
       this.numericPrecision = numericPrecision;
       this.numericPrecisionRadix = numericPrecisionRadix;
       this.numericScale = numericScale;
       this.remarks = remarks;
       this.sequenceCatalog = sequenceCatalog;
       this.sequenceName = sequenceName;
       this.sequenceSchema = sequenceSchema;
       this.startValue = startValue;
    }
   
    public Long getBaseValue() {
        return this.baseValue;
    }
    
    public void setBaseValue(Long baseValue) {
        this.baseValue = baseValue;
    }
    public Long getCache() {
        return this.cache;
    }
    
    public void setCache(Long cache) {
        this.cache = cache;
    }
    public String getCycleOption() {
        return this.cycleOption;
    }
    
    public void setCycleOption(String cycleOption) {
        this.cycleOption = cycleOption;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public String getDeclaredDataType() {
        return this.declaredDataType;
    }
    
    public void setDeclaredDataType(String declaredDataType) {
        this.declaredDataType = declaredDataType;
    }
    public Integer getDeclaredNumericPrecision() {
        return this.declaredNumericPrecision;
    }
    
    public void setDeclaredNumericPrecision(Integer declaredNumericPrecision) {
        this.declaredNumericPrecision = declaredNumericPrecision;
    }
    public Integer getDeclaredNumericScale() {
        return this.declaredNumericScale;
    }
    
    public void setDeclaredNumericScale(Integer declaredNumericScale) {
        this.declaredNumericScale = declaredNumericScale;
    }
    public Long getIncrement() {
        return this.increment;
    }
    
    public void setIncrement(Long increment) {
        this.increment = increment;
    }
    public Long getMaximumValue() {
        return this.maximumValue;
    }
    
    public void setMaximumValue(Long maximumValue) {
        this.maximumValue = maximumValue;
    }
    public Long getMinimumValue() {
        return this.minimumValue;
    }
    
    public void setMinimumValue(Long minimumValue) {
        this.minimumValue = minimumValue;
    }
    public Integer getNumericPrecision() {
        return this.numericPrecision;
    }
    
    public void setNumericPrecision(Integer numericPrecision) {
        this.numericPrecision = numericPrecision;
    }
    public Integer getNumericPrecisionRadix() {
        return this.numericPrecisionRadix;
    }
    
    public void setNumericPrecisionRadix(Integer numericPrecisionRadix) {
        this.numericPrecisionRadix = numericPrecisionRadix;
    }
    public Integer getNumericScale() {
        return this.numericScale;
    }
    
    public void setNumericScale(Integer numericScale) {
        this.numericScale = numericScale;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getSequenceCatalog() {
        return this.sequenceCatalog;
    }
    
    public void setSequenceCatalog(String sequenceCatalog) {
        this.sequenceCatalog = sequenceCatalog;
    }
    public String getSequenceName() {
        return this.sequenceName;
    }
    
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName;
    }
    public String getSequenceSchema() {
        return this.sequenceSchema;
    }
    
    public void setSequenceSchema(String sequenceSchema) {
        this.sequenceSchema = sequenceSchema;
    }
    public Long getStartValue() {
        return this.startValue;
    }
    
    public void setStartValue(Long startValue) {
        this.startValue = startValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SequencesId) ) return false;
		 SequencesId castOther = ( SequencesId ) other; 
         
		 return ( (this.getBaseValue()==castOther.getBaseValue()) || ( this.getBaseValue()!=null && castOther.getBaseValue()!=null && this.getBaseValue().equals(castOther.getBaseValue()) ) )
 && ( (this.getCache()==castOther.getCache()) || ( this.getCache()!=null && castOther.getCache()!=null && this.getCache().equals(castOther.getCache()) ) )
 && ( (this.getCycleOption()==castOther.getCycleOption()) || ( this.getCycleOption()!=null && castOther.getCycleOption()!=null && this.getCycleOption().equals(castOther.getCycleOption()) ) )
 && ( (this.getDataType()==castOther.getDataType()) || ( this.getDataType()!=null && castOther.getDataType()!=null && this.getDataType().equals(castOther.getDataType()) ) )
 && ( (this.getDeclaredDataType()==castOther.getDeclaredDataType()) || ( this.getDeclaredDataType()!=null && castOther.getDeclaredDataType()!=null && this.getDeclaredDataType().equals(castOther.getDeclaredDataType()) ) )
 && ( (this.getDeclaredNumericPrecision()==castOther.getDeclaredNumericPrecision()) || ( this.getDeclaredNumericPrecision()!=null && castOther.getDeclaredNumericPrecision()!=null && this.getDeclaredNumericPrecision().equals(castOther.getDeclaredNumericPrecision()) ) )
 && ( (this.getDeclaredNumericScale()==castOther.getDeclaredNumericScale()) || ( this.getDeclaredNumericScale()!=null && castOther.getDeclaredNumericScale()!=null && this.getDeclaredNumericScale().equals(castOther.getDeclaredNumericScale()) ) )
 && ( (this.getIncrement()==castOther.getIncrement()) || ( this.getIncrement()!=null && castOther.getIncrement()!=null && this.getIncrement().equals(castOther.getIncrement()) ) )
 && ( (this.getMaximumValue()==castOther.getMaximumValue()) || ( this.getMaximumValue()!=null && castOther.getMaximumValue()!=null && this.getMaximumValue().equals(castOther.getMaximumValue()) ) )
 && ( (this.getMinimumValue()==castOther.getMinimumValue()) || ( this.getMinimumValue()!=null && castOther.getMinimumValue()!=null && this.getMinimumValue().equals(castOther.getMinimumValue()) ) )
 && ( (this.getNumericPrecision()==castOther.getNumericPrecision()) || ( this.getNumericPrecision()!=null && castOther.getNumericPrecision()!=null && this.getNumericPrecision().equals(castOther.getNumericPrecision()) ) )
 && ( (this.getNumericPrecisionRadix()==castOther.getNumericPrecisionRadix()) || ( this.getNumericPrecisionRadix()!=null && castOther.getNumericPrecisionRadix()!=null && this.getNumericPrecisionRadix().equals(castOther.getNumericPrecisionRadix()) ) )
 && ( (this.getNumericScale()==castOther.getNumericScale()) || ( this.getNumericScale()!=null && castOther.getNumericScale()!=null && this.getNumericScale().equals(castOther.getNumericScale()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getSequenceCatalog()==castOther.getSequenceCatalog()) || ( this.getSequenceCatalog()!=null && castOther.getSequenceCatalog()!=null && this.getSequenceCatalog().equals(castOther.getSequenceCatalog()) ) )
 && ( (this.getSequenceName()==castOther.getSequenceName()) || ( this.getSequenceName()!=null && castOther.getSequenceName()!=null && this.getSequenceName().equals(castOther.getSequenceName()) ) )
 && ( (this.getSequenceSchema()==castOther.getSequenceSchema()) || ( this.getSequenceSchema()!=null && castOther.getSequenceSchema()!=null && this.getSequenceSchema().equals(castOther.getSequenceSchema()) ) )
 && ( (this.getStartValue()==castOther.getStartValue()) || ( this.getStartValue()!=null && castOther.getStartValue()!=null && this.getStartValue().equals(castOther.getStartValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBaseValue() == null ? 0 : this.getBaseValue().hashCode() );
        result = 37 * result + ( getCache() == null ? 0 : this.getCache().hashCode() );
        result = 37 * result + ( getCycleOption() == null ? 0 : this.getCycleOption().hashCode() );
        result = 37 * result + ( getDataType() == null ? 0 : this.getDataType().hashCode() );
        result = 37 * result + ( getDeclaredDataType() == null ? 0 : this.getDeclaredDataType().hashCode() );
        result = 37 * result + ( getDeclaredNumericPrecision() == null ? 0 : this.getDeclaredNumericPrecision().hashCode() );
        result = 37 * result + ( getDeclaredNumericScale() == null ? 0 : this.getDeclaredNumericScale().hashCode() );
        result = 37 * result + ( getIncrement() == null ? 0 : this.getIncrement().hashCode() );
        result = 37 * result + ( getMaximumValue() == null ? 0 : this.getMaximumValue().hashCode() );
        result = 37 * result + ( getMinimumValue() == null ? 0 : this.getMinimumValue().hashCode() );
        result = 37 * result + ( getNumericPrecision() == null ? 0 : this.getNumericPrecision().hashCode() );
        result = 37 * result + ( getNumericPrecisionRadix() == null ? 0 : this.getNumericPrecisionRadix().hashCode() );
        result = 37 * result + ( getNumericScale() == null ? 0 : this.getNumericScale().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getSequenceCatalog() == null ? 0 : this.getSequenceCatalog().hashCode() );
        result = 37 * result + ( getSequenceName() == null ? 0 : this.getSequenceName().hashCode() );
        result = 37 * result + ( getSequenceSchema() == null ? 0 : this.getSequenceSchema().hashCode() );
        result = 37 * result + ( getStartValue() == null ? 0 : this.getStartValue().hashCode() );
         return result;
   }   


}


