// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private SessionsId id;

    public Sessions() {
    }

    public Sessions(SessionsId id) {
       this.id = id;
    }
   
    public SessionsId getId() {
        return this.id;
    }
    
    public void setId(SessionsId id) {
        this.id = id;
    }




}


