// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.io.Serializable;

/**
 * SessionsId generated by hbm2java
 */
public class SessionsId  implements java.io.Serializable {


     private Integer blockerId;
     private String clientAddr;
     private String clientInfo;
     private Boolean containsUncommitted;
     private String executingStatement;
     private Serializable executingStatementStart;
     private String isolationLevel;
     private String server;
     private Integer sessionId;
     private Serializable sessionStart;
     private String sessionState;
     private Serializable sleepSince;
     private String userName;

    public SessionsId() {
    }

    public SessionsId(Integer blockerId, String clientAddr, String clientInfo, Boolean containsUncommitted, String executingStatement, Serializable executingStatementStart, String isolationLevel, String server, Integer sessionId, Serializable sessionStart, String sessionState, Serializable sleepSince, String userName) {
       this.blockerId = blockerId;
       this.clientAddr = clientAddr;
       this.clientInfo = clientInfo;
       this.containsUncommitted = containsUncommitted;
       this.executingStatement = executingStatement;
       this.executingStatementStart = executingStatementStart;
       this.isolationLevel = isolationLevel;
       this.server = server;
       this.sessionId = sessionId;
       this.sessionStart = sessionStart;
       this.sessionState = sessionState;
       this.sleepSince = sleepSince;
       this.userName = userName;
    }
   
    public Integer getBlockerId() {
        return this.blockerId;
    }
    
    public void setBlockerId(Integer blockerId) {
        this.blockerId = blockerId;
    }
    public String getClientAddr() {
        return this.clientAddr;
    }
    
    public void setClientAddr(String clientAddr) {
        this.clientAddr = clientAddr;
    }
    public String getClientInfo() {
        return this.clientInfo;
    }
    
    public void setClientInfo(String clientInfo) {
        this.clientInfo = clientInfo;
    }
    public Boolean getContainsUncommitted() {
        return this.containsUncommitted;
    }
    
    public void setContainsUncommitted(Boolean containsUncommitted) {
        this.containsUncommitted = containsUncommitted;
    }
    public String getExecutingStatement() {
        return this.executingStatement;
    }
    
    public void setExecutingStatement(String executingStatement) {
        this.executingStatement = executingStatement;
    }
    public Serializable getExecutingStatementStart() {
        return this.executingStatementStart;
    }
    
    public void setExecutingStatementStart(Serializable executingStatementStart) {
        this.executingStatementStart = executingStatementStart;
    }
    public String getIsolationLevel() {
        return this.isolationLevel;
    }
    
    public void setIsolationLevel(String isolationLevel) {
        this.isolationLevel = isolationLevel;
    }
    public String getServer() {
        return this.server;
    }
    
    public void setServer(String server) {
        this.server = server;
    }
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }
    public Serializable getSessionStart() {
        return this.sessionStart;
    }
    
    public void setSessionStart(Serializable sessionStart) {
        this.sessionStart = sessionStart;
    }
    public String getSessionState() {
        return this.sessionState;
    }
    
    public void setSessionState(String sessionState) {
        this.sessionState = sessionState;
    }
    public Serializable getSleepSince() {
        return this.sleepSince;
    }
    
    public void setSleepSince(Serializable sleepSince) {
        this.sleepSince = sleepSince;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SessionsId) ) return false;
		 SessionsId castOther = ( SessionsId ) other; 
         
		 return ( (this.getBlockerId()==castOther.getBlockerId()) || ( this.getBlockerId()!=null && castOther.getBlockerId()!=null && this.getBlockerId().equals(castOther.getBlockerId()) ) )
 && ( (this.getClientAddr()==castOther.getClientAddr()) || ( this.getClientAddr()!=null && castOther.getClientAddr()!=null && this.getClientAddr().equals(castOther.getClientAddr()) ) )
 && ( (this.getClientInfo()==castOther.getClientInfo()) || ( this.getClientInfo()!=null && castOther.getClientInfo()!=null && this.getClientInfo().equals(castOther.getClientInfo()) ) )
 && ( (this.getContainsUncommitted()==castOther.getContainsUncommitted()) || ( this.getContainsUncommitted()!=null && castOther.getContainsUncommitted()!=null && this.getContainsUncommitted().equals(castOther.getContainsUncommitted()) ) )
 && ( (this.getExecutingStatement()==castOther.getExecutingStatement()) || ( this.getExecutingStatement()!=null && castOther.getExecutingStatement()!=null && this.getExecutingStatement().equals(castOther.getExecutingStatement()) ) )
 && ( (this.getExecutingStatementStart()==castOther.getExecutingStatementStart()) || ( this.getExecutingStatementStart()!=null && castOther.getExecutingStatementStart()!=null && this.getExecutingStatementStart().equals(castOther.getExecutingStatementStart()) ) )
 && ( (this.getIsolationLevel()==castOther.getIsolationLevel()) || ( this.getIsolationLevel()!=null && castOther.getIsolationLevel()!=null && this.getIsolationLevel().equals(castOther.getIsolationLevel()) ) )
 && ( (this.getServer()==castOther.getServer()) || ( this.getServer()!=null && castOther.getServer()!=null && this.getServer().equals(castOther.getServer()) ) )
 && ( (this.getSessionId()==castOther.getSessionId()) || ( this.getSessionId()!=null && castOther.getSessionId()!=null && this.getSessionId().equals(castOther.getSessionId()) ) )
 && ( (this.getSessionStart()==castOther.getSessionStart()) || ( this.getSessionStart()!=null && castOther.getSessionStart()!=null && this.getSessionStart().equals(castOther.getSessionStart()) ) )
 && ( (this.getSessionState()==castOther.getSessionState()) || ( this.getSessionState()!=null && castOther.getSessionState()!=null && this.getSessionState().equals(castOther.getSessionState()) ) )
 && ( (this.getSleepSince()==castOther.getSleepSince()) || ( this.getSleepSince()!=null && castOther.getSleepSince()!=null && this.getSleepSince().equals(castOther.getSleepSince()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBlockerId() == null ? 0 : this.getBlockerId().hashCode() );
        result = 37 * result + ( getClientAddr() == null ? 0 : this.getClientAddr().hashCode() );
        result = 37 * result + ( getClientInfo() == null ? 0 : this.getClientInfo().hashCode() );
        result = 37 * result + ( getContainsUncommitted() == null ? 0 : this.getContainsUncommitted().hashCode() );
        result = 37 * result + ( getExecutingStatement() == null ? 0 : this.getExecutingStatement().hashCode() );
        result = 37 * result + ( getExecutingStatementStart() == null ? 0 : this.getExecutingStatementStart().hashCode() );
        result = 37 * result + ( getIsolationLevel() == null ? 0 : this.getIsolationLevel().hashCode() );
        result = 37 * result + ( getServer() == null ? 0 : this.getServer().hashCode() );
        result = 37 * result + ( getSessionId() == null ? 0 : this.getSessionId().hashCode() );
        result = 37 * result + ( getSessionStart() == null ? 0 : this.getSessionStart().hashCode() );
        result = 37 * result + ( getSessionState() == null ? 0 : this.getSessionState().hashCode() );
        result = 37 * result + ( getSleepSince() == null ? 0 : this.getSleepSince().hashCode() );
        result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


