// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SessionState generated by hbm2java
 */
public class SessionState  implements java.io.Serializable {


     private SessionStateId id;

    public SessionState() {
    }

    public SessionState(SessionStateId id) {
       this.id = id;
    }
   
    public SessionStateId getId() {
        return this.id;
    }
    
    public void setId(SessionStateId id) {
        this.id = id;
    }




}


