// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SessionStateId generated by hbm2java
 */
public class SessionStateId  implements java.io.Serializable {


     private String stateCommand;
     private String stateKey;

    public SessionStateId() {
    }

    public SessionStateId(String stateCommand, String stateKey) {
       this.stateCommand = stateCommand;
       this.stateKey = stateKey;
    }
   
    public String getStateCommand() {
        return this.stateCommand;
    }
    
    public void setStateCommand(String stateCommand) {
        this.stateCommand = stateCommand;
    }
    public String getStateKey() {
        return this.stateKey;
    }
    
    public void setStateKey(String stateKey) {
        this.stateKey = stateKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SessionStateId) ) return false;
		 SessionStateId castOther = ( SessionStateId ) other; 
         
		 return ( (this.getStateCommand()==castOther.getStateCommand()) || ( this.getStateCommand()!=null && castOther.getStateCommand()!=null && this.getStateCommand().equals(castOther.getStateCommand()) ) )
 && ( (this.getStateKey()==castOther.getStateKey()) || ( this.getStateKey()!=null && castOther.getStateKey()!=null && this.getStateKey().equals(castOther.getStateKey()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getStateCommand() == null ? 0 : this.getStateCommand().hashCode() );
        result = 37 * result + ( getStateKey() == null ? 0 : this.getStateKey().hashCode() );
         return result;
   }   


}


