// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SettingsId generated by hbm2java
 */
public class SettingsId  implements java.io.Serializable {


     private String settingName;
     private String settingValue;

    public SettingsId() {
    }

    public SettingsId(String settingName, String settingValue) {
       this.settingName = settingName;
       this.settingValue = settingValue;
    }
   
    public String getSettingName() {
        return this.settingName;
    }
    
    public void setSettingName(String settingName) {
        this.settingName = settingName;
    }
    public String getSettingValue() {
        return this.settingValue;
    }
    
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SettingsId) ) return false;
		 SettingsId castOther = ( SettingsId ) other; 
         
		 return ( (this.getSettingName()==castOther.getSettingName()) || ( this.getSettingName()!=null && castOther.getSettingName()!=null && this.getSettingName().equals(castOther.getSettingName()) ) )
 && ( (this.getSettingValue()==castOther.getSettingValue()) || ( this.getSettingValue()!=null && castOther.getSettingValue()!=null && this.getSettingValue().equals(castOther.getSettingValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getSettingName() == null ? 0 : this.getSettingName().hashCode() );
        result = 37 * result + ( getSettingValue() == null ? 0 : this.getSettingValue().hashCode() );
         return result;
   }   


}


