// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Settings generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


     private SettingsId id;

    public Settings() {
    }

    public Settings(SettingsId id) {
       this.id = id;
    }
   
    public SettingsId getId() {
        return this.id;
    }
    
    public void setId(SettingsId id) {
        this.id = id;
    }




}


