// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private byte storeId;
     private Address address;
     private Staff staff;
     private Timestamp lastUpdate;
     private Set staffs = new HashSet(0);
     private Set inventories = new HashSet(0);
     private Set customers = new HashSet(0);

    public Store() {
    }

	
    public Store(byte storeId, Address address, Staff staff, Timestamp lastUpdate) {
        this.storeId = storeId;
        this.address = address;
        this.staff = staff;
        this.lastUpdate = lastUpdate;
    }
    public Store(byte storeId, Address address, Staff staff, Timestamp lastUpdate, Set staffs, Set inventories, Set customers) {
       this.storeId = storeId;
       this.address = address;
       this.staff = staff;
       this.lastUpdate = lastUpdate;
       this.staffs = staffs;
       this.inventories = inventories;
       this.customers = customers;
    }
   
    public byte getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(byte storeId) {
        this.storeId = storeId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }
    public Set getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set inventories) {
        this.inventories = inventories;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


