// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Synonyms generated by hbm2java
 */
public class Synonyms  implements java.io.Serializable {


     private SynonymsId id;

    public Synonyms() {
    }

    public Synonyms(SynonymsId id) {
       this.id = id;
    }
   
    public SynonymsId getId() {
        return this.id;
    }
    
    public void setId(SynonymsId id) {
        this.id = id;
    }




}


