// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * SynonymsId generated by hbm2java
 */
public class SynonymsId  implements java.io.Serializable {


     private String remarks;
     private String status;
     private String synonymCatalog;
     private String synonymFor;
     private String synonymForSchema;
     private String synonymName;
     private String synonymSchema;
     private String typeName;

    public SynonymsId() {
    }

    public SynonymsId(String remarks, String status, String synonymCatalog, String synonymFor, String synonymForSchema, String synonymName, String synonymSchema, String typeName) {
       this.remarks = remarks;
       this.status = status;
       this.synonymCatalog = synonymCatalog;
       this.synonymFor = synonymFor;
       this.synonymForSchema = synonymForSchema;
       this.synonymName = synonymName;
       this.synonymSchema = synonymSchema;
       this.typeName = typeName;
    }
   
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getSynonymCatalog() {
        return this.synonymCatalog;
    }
    
    public void setSynonymCatalog(String synonymCatalog) {
        this.synonymCatalog = synonymCatalog;
    }
    public String getSynonymFor() {
        return this.synonymFor;
    }
    
    public void setSynonymFor(String synonymFor) {
        this.synonymFor = synonymFor;
    }
    public String getSynonymForSchema() {
        return this.synonymForSchema;
    }
    
    public void setSynonymForSchema(String synonymForSchema) {
        this.synonymForSchema = synonymForSchema;
    }
    public String getSynonymName() {
        return this.synonymName;
    }
    
    public void setSynonymName(String synonymName) {
        this.synonymName = synonymName;
    }
    public String getSynonymSchema() {
        return this.synonymSchema;
    }
    
    public void setSynonymSchema(String synonymSchema) {
        this.synonymSchema = synonymSchema;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SynonymsId) ) return false;
		 SynonymsId castOther = ( SynonymsId ) other; 
         
		 return ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getSynonymCatalog()==castOther.getSynonymCatalog()) || ( this.getSynonymCatalog()!=null && castOther.getSynonymCatalog()!=null && this.getSynonymCatalog().equals(castOther.getSynonymCatalog()) ) )
 && ( (this.getSynonymFor()==castOther.getSynonymFor()) || ( this.getSynonymFor()!=null && castOther.getSynonymFor()!=null && this.getSynonymFor().equals(castOther.getSynonymFor()) ) )
 && ( (this.getSynonymForSchema()==castOther.getSynonymForSchema()) || ( this.getSynonymForSchema()!=null && castOther.getSynonymForSchema()!=null && this.getSynonymForSchema().equals(castOther.getSynonymForSchema()) ) )
 && ( (this.getSynonymName()==castOther.getSynonymName()) || ( this.getSynonymName()!=null && castOther.getSynonymName()!=null && this.getSynonymName().equals(castOther.getSynonymName()) ) )
 && ( (this.getSynonymSchema()==castOther.getSynonymSchema()) || ( this.getSynonymSchema()!=null && castOther.getSynonymSchema()!=null && this.getSynonymSchema().equals(castOther.getSynonymSchema()) ) )
 && ( (this.getTypeName()==castOther.getTypeName()) || ( this.getTypeName()!=null && castOther.getTypeName()!=null && this.getTypeName().equals(castOther.getTypeName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
        result = 37 * result + ( getSynonymCatalog() == null ? 0 : this.getSynonymCatalog().hashCode() );
        result = 37 * result + ( getSynonymFor() == null ? 0 : this.getSynonymFor().hashCode() );
        result = 37 * result + ( getSynonymForSchema() == null ? 0 : this.getSynonymForSchema().hashCode() );
        result = 37 * result + ( getSynonymName() == null ? 0 : this.getSynonymName().hashCode() );
        result = 37 * result + ( getSynonymSchema() == null ? 0 : this.getSynonymSchema().hashCode() );
        result = 37 * result + ( getTypeName() == null ? 0 : this.getTypeName().hashCode() );
         return result;
   }   


}


