// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TablePrivileges generated by hbm2java
 */
public class TablePrivileges  implements java.io.Serializable {


     private TablePrivilegesId id;

    public TablePrivileges() {
    }

    public TablePrivileges(TablePrivilegesId id) {
       this.id = id;
    }
   
    public TablePrivilegesId getId() {
        return this.id;
    }
    
    public void setId(TablePrivilegesId id) {
        this.id = id;
    }




}


