// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TablePrivilegesId generated by hbm2java
 */
public class TablePrivilegesId  implements java.io.Serializable {


     private String grantee;
     private String grantor;
     private String isGrantable;
     private String privilegeType;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;
     private String withHierarchy;

    public TablePrivilegesId() {
    }

    public TablePrivilegesId(String grantee, String grantor, String isGrantable, String privilegeType, String tableCatalog, String tableName, String tableSchema, String withHierarchy) {
       this.grantee = grantee;
       this.grantor = grantor;
       this.isGrantable = isGrantable;
       this.privilegeType = privilegeType;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
       this.withHierarchy = withHierarchy;
    }
   
    public String getGrantee() {
        return this.grantee;
    }
    
    public void setGrantee(String grantee) {
        this.grantee = grantee;
    }
    public String getGrantor() {
        return this.grantor;
    }
    
    public void setGrantor(String grantor) {
        this.grantor = grantor;
    }
    public String getIsGrantable() {
        return this.isGrantable;
    }
    
    public void setIsGrantable(String isGrantable) {
        this.isGrantable = isGrantable;
    }
    public String getPrivilegeType() {
        return this.privilegeType;
    }
    
    public void setPrivilegeType(String privilegeType) {
        this.privilegeType = privilegeType;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }
    public String getWithHierarchy() {
        return this.withHierarchy;
    }
    
    public void setWithHierarchy(String withHierarchy) {
        this.withHierarchy = withHierarchy;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TablePrivilegesId) ) return false;
		 TablePrivilegesId castOther = ( TablePrivilegesId ) other; 
         
		 return ( (this.getGrantee()==castOther.getGrantee()) || ( this.getGrantee()!=null && castOther.getGrantee()!=null && this.getGrantee().equals(castOther.getGrantee()) ) )
 && ( (this.getGrantor()==castOther.getGrantor()) || ( this.getGrantor()!=null && castOther.getGrantor()!=null && this.getGrantor().equals(castOther.getGrantor()) ) )
 && ( (this.getIsGrantable()==castOther.getIsGrantable()) || ( this.getIsGrantable()!=null && castOther.getIsGrantable()!=null && this.getIsGrantable().equals(castOther.getIsGrantable()) ) )
 && ( (this.getPrivilegeType()==castOther.getPrivilegeType()) || ( this.getPrivilegeType()!=null && castOther.getPrivilegeType()!=null && this.getPrivilegeType().equals(castOther.getPrivilegeType()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) )
 && ( (this.getWithHierarchy()==castOther.getWithHierarchy()) || ( this.getWithHierarchy()!=null && castOther.getWithHierarchy()!=null && this.getWithHierarchy().equals(castOther.getWithHierarchy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getGrantee() == null ? 0 : this.getGrantee().hashCode() );
        result = 37 * result + ( getGrantor() == null ? 0 : this.getGrantor().hashCode() );
        result = 37 * result + ( getIsGrantable() == null ? 0 : this.getIsGrantable().hashCode() );
        result = 37 * result + ( getPrivilegeType() == null ? 0 : this.getPrivilegeType().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
        result = 37 * result + ( getWithHierarchy() == null ? 0 : this.getWithHierarchy().hashCode() );
         return result;
   }   


}


