// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TableConstraintsId generated by hbm2java
 */
public class TableConstraintsId  implements java.io.Serializable {


     private String constraintCatalog;
     private String constraintName;
     private String constraintSchema;
     private String constraintType;
     private String enforced;
     private String indexCatalog;
     private String indexName;
     private String indexSchema;
     private String initiallyDeferred;
     private String isDeferrable;
     private String nullsDistinct;
     private String remarks;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;

    public TableConstraintsId() {
    }

    public TableConstraintsId(String constraintCatalog, String constraintName, String constraintSchema, String constraintType, String enforced, String indexCatalog, String indexName, String indexSchema, String initiallyDeferred, String isDeferrable, String nullsDistinct, String remarks, String tableCatalog, String tableName, String tableSchema) {
       this.constraintCatalog = constraintCatalog;
       this.constraintName = constraintName;
       this.constraintSchema = constraintSchema;
       this.constraintType = constraintType;
       this.enforced = enforced;
       this.indexCatalog = indexCatalog;
       this.indexName = indexName;
       this.indexSchema = indexSchema;
       this.initiallyDeferred = initiallyDeferred;
       this.isDeferrable = isDeferrable;
       this.nullsDistinct = nullsDistinct;
       this.remarks = remarks;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
    }
   
    public String getConstraintCatalog() {
        return this.constraintCatalog;
    }
    
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog;
    }
    public String getConstraintName() {
        return this.constraintName;
    }
    
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName;
    }
    public String getConstraintSchema() {
        return this.constraintSchema;
    }
    
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema;
    }
    public String getConstraintType() {
        return this.constraintType;
    }
    
    public void setConstraintType(String constraintType) {
        this.constraintType = constraintType;
    }
    public String getEnforced() {
        return this.enforced;
    }
    
    public void setEnforced(String enforced) {
        this.enforced = enforced;
    }
    public String getIndexCatalog() {
        return this.indexCatalog;
    }
    
    public void setIndexCatalog(String indexCatalog) {
        this.indexCatalog = indexCatalog;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    public String getIndexSchema() {
        return this.indexSchema;
    }
    
    public void setIndexSchema(String indexSchema) {
        this.indexSchema = indexSchema;
    }
    public String getInitiallyDeferred() {
        return this.initiallyDeferred;
    }
    
    public void setInitiallyDeferred(String initiallyDeferred) {
        this.initiallyDeferred = initiallyDeferred;
    }
    public String getIsDeferrable() {
        return this.isDeferrable;
    }
    
    public void setIsDeferrable(String isDeferrable) {
        this.isDeferrable = isDeferrable;
    }
    public String getNullsDistinct() {
        return this.nullsDistinct;
    }
    
    public void setNullsDistinct(String nullsDistinct) {
        this.nullsDistinct = nullsDistinct;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TableConstraintsId) ) return false;
		 TableConstraintsId castOther = ( TableConstraintsId ) other; 
         
		 return ( (this.getConstraintCatalog()==castOther.getConstraintCatalog()) || ( this.getConstraintCatalog()!=null && castOther.getConstraintCatalog()!=null && this.getConstraintCatalog().equals(castOther.getConstraintCatalog()) ) )
 && ( (this.getConstraintName()==castOther.getConstraintName()) || ( this.getConstraintName()!=null && castOther.getConstraintName()!=null && this.getConstraintName().equals(castOther.getConstraintName()) ) )
 && ( (this.getConstraintSchema()==castOther.getConstraintSchema()) || ( this.getConstraintSchema()!=null && castOther.getConstraintSchema()!=null && this.getConstraintSchema().equals(castOther.getConstraintSchema()) ) )
 && ( (this.getConstraintType()==castOther.getConstraintType()) || ( this.getConstraintType()!=null && castOther.getConstraintType()!=null && this.getConstraintType().equals(castOther.getConstraintType()) ) )
 && ( (this.getEnforced()==castOther.getEnforced()) || ( this.getEnforced()!=null && castOther.getEnforced()!=null && this.getEnforced().equals(castOther.getEnforced()) ) )
 && ( (this.getIndexCatalog()==castOther.getIndexCatalog()) || ( this.getIndexCatalog()!=null && castOther.getIndexCatalog()!=null && this.getIndexCatalog().equals(castOther.getIndexCatalog()) ) )
 && ( (this.getIndexName()==castOther.getIndexName()) || ( this.getIndexName()!=null && castOther.getIndexName()!=null && this.getIndexName().equals(castOther.getIndexName()) ) )
 && ( (this.getIndexSchema()==castOther.getIndexSchema()) || ( this.getIndexSchema()!=null && castOther.getIndexSchema()!=null && this.getIndexSchema().equals(castOther.getIndexSchema()) ) )
 && ( (this.getInitiallyDeferred()==castOther.getInitiallyDeferred()) || ( this.getInitiallyDeferred()!=null && castOther.getInitiallyDeferred()!=null && this.getInitiallyDeferred().equals(castOther.getInitiallyDeferred()) ) )
 && ( (this.getIsDeferrable()==castOther.getIsDeferrable()) || ( this.getIsDeferrable()!=null && castOther.getIsDeferrable()!=null && this.getIsDeferrable().equals(castOther.getIsDeferrable()) ) )
 && ( (this.getNullsDistinct()==castOther.getNullsDistinct()) || ( this.getNullsDistinct()!=null && castOther.getNullsDistinct()!=null && this.getNullsDistinct().equals(castOther.getNullsDistinct()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getConstraintCatalog() == null ? 0 : this.getConstraintCatalog().hashCode() );
        result = 37 * result + ( getConstraintName() == null ? 0 : this.getConstraintName().hashCode() );
        result = 37 * result + ( getConstraintSchema() == null ? 0 : this.getConstraintSchema().hashCode() );
        result = 37 * result + ( getConstraintType() == null ? 0 : this.getConstraintType().hashCode() );
        result = 37 * result + ( getEnforced() == null ? 0 : this.getEnforced().hashCode() );
        result = 37 * result + ( getIndexCatalog() == null ? 0 : this.getIndexCatalog().hashCode() );
        result = 37 * result + ( getIndexName() == null ? 0 : this.getIndexName().hashCode() );
        result = 37 * result + ( getIndexSchema() == null ? 0 : this.getIndexSchema().hashCode() );
        result = 37 * result + ( getInitiallyDeferred() == null ? 0 : this.getInitiallyDeferred().hashCode() );
        result = 37 * result + ( getIsDeferrable() == null ? 0 : this.getIsDeferrable().hashCode() );
        result = 37 * result + ( getNullsDistinct() == null ? 0 : this.getNullsDistinct().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
         return result;
   }   


}


