// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TablesId generated by hbm2java
 */
public class TablesId  implements java.io.Serializable {


     private String commitAction;
     private String isInsertableInto;
     private Long lastModification;
     private String remarks;
     private Long rowCountEstimate;
     private String storageType;
     private String tableCatalog;
     private String tableClass;
     private String tableName;
     private String tableSchema;
     private String tableType;

    public TablesId() {
    }

    public TablesId(String commitAction, String isInsertableInto, Long lastModification, String remarks, Long rowCountEstimate, String storageType, String tableCatalog, String tableClass, String tableName, String tableSchema, String tableType) {
       this.commitAction = commitAction;
       this.isInsertableInto = isInsertableInto;
       this.lastModification = lastModification;
       this.remarks = remarks;
       this.rowCountEstimate = rowCountEstimate;
       this.storageType = storageType;
       this.tableCatalog = tableCatalog;
       this.tableClass = tableClass;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
       this.tableType = tableType;
    }
   
    public String getCommitAction() {
        return this.commitAction;
    }
    
    public void setCommitAction(String commitAction) {
        this.commitAction = commitAction;
    }
    public String getIsInsertableInto() {
        return this.isInsertableInto;
    }
    
    public void setIsInsertableInto(String isInsertableInto) {
        this.isInsertableInto = isInsertableInto;
    }
    public Long getLastModification() {
        return this.lastModification;
    }
    
    public void setLastModification(Long lastModification) {
        this.lastModification = lastModification;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Long getRowCountEstimate() {
        return this.rowCountEstimate;
    }
    
    public void setRowCountEstimate(Long rowCountEstimate) {
        this.rowCountEstimate = rowCountEstimate;
    }
    public String getStorageType() {
        return this.storageType;
    }
    
    public void setStorageType(String storageType) {
        this.storageType = storageType;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableClass() {
        return this.tableClass;
    }
    
    public void setTableClass(String tableClass) {
        this.tableClass = tableClass;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }
    public String getTableType() {
        return this.tableType;
    }
    
    public void setTableType(String tableType) {
        this.tableType = tableType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TablesId) ) return false;
		 TablesId castOther = ( TablesId ) other; 
         
		 return ( (this.getCommitAction()==castOther.getCommitAction()) || ( this.getCommitAction()!=null && castOther.getCommitAction()!=null && this.getCommitAction().equals(castOther.getCommitAction()) ) )
 && ( (this.getIsInsertableInto()==castOther.getIsInsertableInto()) || ( this.getIsInsertableInto()!=null && castOther.getIsInsertableInto()!=null && this.getIsInsertableInto().equals(castOther.getIsInsertableInto()) ) )
 && ( (this.getLastModification()==castOther.getLastModification()) || ( this.getLastModification()!=null && castOther.getLastModification()!=null && this.getLastModification().equals(castOther.getLastModification()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getRowCountEstimate()==castOther.getRowCountEstimate()) || ( this.getRowCountEstimate()!=null && castOther.getRowCountEstimate()!=null && this.getRowCountEstimate().equals(castOther.getRowCountEstimate()) ) )
 && ( (this.getStorageType()==castOther.getStorageType()) || ( this.getStorageType()!=null && castOther.getStorageType()!=null && this.getStorageType().equals(castOther.getStorageType()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableClass()==castOther.getTableClass()) || ( this.getTableClass()!=null && castOther.getTableClass()!=null && this.getTableClass().equals(castOther.getTableClass()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) )
 && ( (this.getTableType()==castOther.getTableType()) || ( this.getTableType()!=null && castOther.getTableType()!=null && this.getTableType().equals(castOther.getTableType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCommitAction() == null ? 0 : this.getCommitAction().hashCode() );
        result = 37 * result + ( getIsInsertableInto() == null ? 0 : this.getIsInsertableInto().hashCode() );
        result = 37 * result + ( getLastModification() == null ? 0 : this.getLastModification().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getRowCountEstimate() == null ? 0 : this.getRowCountEstimate().hashCode() );
        result = 37 * result + ( getStorageType() == null ? 0 : this.getStorageType().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableClass() == null ? 0 : this.getTableClass().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
        result = 37 * result + ( getTableType() == null ? 0 : this.getTableType().hashCode() );
         return result;
   }   


}


