// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TableConstraints generated by hbm2java
 */
public class TableConstraints  implements java.io.Serializable {


     private TableConstraintsId id;

    public TableConstraints() {
    }

    public TableConstraints(TableConstraintsId id) {
       this.id = id;
    }
   
    public TableConstraintsId getId() {
        return this.id;
    }
    
    public void setId(TableConstraintsId id) {
        this.id = id;
    }




}


