// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Triggers generated by hbm2java
 */
public class Triggers  implements java.io.Serializable {


     private TriggersId id;

    public Triggers() {
    }

    public Triggers(TriggersId id) {
       this.id = id;
    }
   
    public TriggersId getId() {
        return this.id;
    }
    
    public void setId(TriggersId id) {
        this.id = id;
    }




}


