// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * TriggersId generated by hbm2java
 */
public class TriggersId  implements java.io.Serializable {


     private String actionOrientation;
     private String actionTiming;
     private String eventManipulation;
     private String eventObjectCatalog;
     private String eventObjectSchema;
     private String eventObjectTable;
     private Boolean isRollback;
     private String javaClass;
     private Boolean noWait;
     private Integer queueSize;
     private String remarks;
     private String triggerCatalog;
     private String triggerName;
     private String triggerSchema;

    public TriggersId() {
    }

    public TriggersId(String actionOrientation, String actionTiming, String eventManipulation, String eventObjectCatalog, String eventObjectSchema, String eventObjectTable, Boolean isRollback, String javaClass, Boolean noWait, Integer queueSize, String remarks, String triggerCatalog, String triggerName, String triggerSchema) {
       this.actionOrientation = actionOrientation;
       this.actionTiming = actionTiming;
       this.eventManipulation = eventManipulation;
       this.eventObjectCatalog = eventObjectCatalog;
       this.eventObjectSchema = eventObjectSchema;
       this.eventObjectTable = eventObjectTable;
       this.isRollback = isRollback;
       this.javaClass = javaClass;
       this.noWait = noWait;
       this.queueSize = queueSize;
       this.remarks = remarks;
       this.triggerCatalog = triggerCatalog;
       this.triggerName = triggerName;
       this.triggerSchema = triggerSchema;
    }
   
    public String getActionOrientation() {
        return this.actionOrientation;
    }
    
    public void setActionOrientation(String actionOrientation) {
        this.actionOrientation = actionOrientation;
    }
    public String getActionTiming() {
        return this.actionTiming;
    }
    
    public void setActionTiming(String actionTiming) {
        this.actionTiming = actionTiming;
    }
    public String getEventManipulation() {
        return this.eventManipulation;
    }
    
    public void setEventManipulation(String eventManipulation) {
        this.eventManipulation = eventManipulation;
    }
    public String getEventObjectCatalog() {
        return this.eventObjectCatalog;
    }
    
    public void setEventObjectCatalog(String eventObjectCatalog) {
        this.eventObjectCatalog = eventObjectCatalog;
    }
    public String getEventObjectSchema() {
        return this.eventObjectSchema;
    }
    
    public void setEventObjectSchema(String eventObjectSchema) {
        this.eventObjectSchema = eventObjectSchema;
    }
    public String getEventObjectTable() {
        return this.eventObjectTable;
    }
    
    public void setEventObjectTable(String eventObjectTable) {
        this.eventObjectTable = eventObjectTable;
    }
    public Boolean getIsRollback() {
        return this.isRollback;
    }
    
    public void setIsRollback(Boolean isRollback) {
        this.isRollback = isRollback;
    }
    public String getJavaClass() {
        return this.javaClass;
    }
    
    public void setJavaClass(String javaClass) {
        this.javaClass = javaClass;
    }
    public Boolean getNoWait() {
        return this.noWait;
    }
    
    public void setNoWait(Boolean noWait) {
        this.noWait = noWait;
    }
    public Integer getQueueSize() {
        return this.queueSize;
    }
    
    public void setQueueSize(Integer queueSize) {
        this.queueSize = queueSize;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getTriggerCatalog() {
        return this.triggerCatalog;
    }
    
    public void setTriggerCatalog(String triggerCatalog) {
        this.triggerCatalog = triggerCatalog;
    }
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    public String getTriggerSchema() {
        return this.triggerSchema;
    }
    
    public void setTriggerSchema(String triggerSchema) {
        this.triggerSchema = triggerSchema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TriggersId) ) return false;
		 TriggersId castOther = ( TriggersId ) other; 
         
		 return ( (this.getActionOrientation()==castOther.getActionOrientation()) || ( this.getActionOrientation()!=null && castOther.getActionOrientation()!=null && this.getActionOrientation().equals(castOther.getActionOrientation()) ) )
 && ( (this.getActionTiming()==castOther.getActionTiming()) || ( this.getActionTiming()!=null && castOther.getActionTiming()!=null && this.getActionTiming().equals(castOther.getActionTiming()) ) )
 && ( (this.getEventManipulation()==castOther.getEventManipulation()) || ( this.getEventManipulation()!=null && castOther.getEventManipulation()!=null && this.getEventManipulation().equals(castOther.getEventManipulation()) ) )
 && ( (this.getEventObjectCatalog()==castOther.getEventObjectCatalog()) || ( this.getEventObjectCatalog()!=null && castOther.getEventObjectCatalog()!=null && this.getEventObjectCatalog().equals(castOther.getEventObjectCatalog()) ) )
 && ( (this.getEventObjectSchema()==castOther.getEventObjectSchema()) || ( this.getEventObjectSchema()!=null && castOther.getEventObjectSchema()!=null && this.getEventObjectSchema().equals(castOther.getEventObjectSchema()) ) )
 && ( (this.getEventObjectTable()==castOther.getEventObjectTable()) || ( this.getEventObjectTable()!=null && castOther.getEventObjectTable()!=null && this.getEventObjectTable().equals(castOther.getEventObjectTable()) ) )
 && ( (this.getIsRollback()==castOther.getIsRollback()) || ( this.getIsRollback()!=null && castOther.getIsRollback()!=null && this.getIsRollback().equals(castOther.getIsRollback()) ) )
 && ( (this.getJavaClass()==castOther.getJavaClass()) || ( this.getJavaClass()!=null && castOther.getJavaClass()!=null && this.getJavaClass().equals(castOther.getJavaClass()) ) )
 && ( (this.getNoWait()==castOther.getNoWait()) || ( this.getNoWait()!=null && castOther.getNoWait()!=null && this.getNoWait().equals(castOther.getNoWait()) ) )
 && ( (this.getQueueSize()==castOther.getQueueSize()) || ( this.getQueueSize()!=null && castOther.getQueueSize()!=null && this.getQueueSize().equals(castOther.getQueueSize()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getTriggerCatalog()==castOther.getTriggerCatalog()) || ( this.getTriggerCatalog()!=null && castOther.getTriggerCatalog()!=null && this.getTriggerCatalog().equals(castOther.getTriggerCatalog()) ) )
 && ( (this.getTriggerName()==castOther.getTriggerName()) || ( this.getTriggerName()!=null && castOther.getTriggerName()!=null && this.getTriggerName().equals(castOther.getTriggerName()) ) )
 && ( (this.getTriggerSchema()==castOther.getTriggerSchema()) || ( this.getTriggerSchema()!=null && castOther.getTriggerSchema()!=null && this.getTriggerSchema().equals(castOther.getTriggerSchema()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getActionOrientation() == null ? 0 : this.getActionOrientation().hashCode() );
        result = 37 * result + ( getActionTiming() == null ? 0 : this.getActionTiming().hashCode() );
        result = 37 * result + ( getEventManipulation() == null ? 0 : this.getEventManipulation().hashCode() );
        result = 37 * result + ( getEventObjectCatalog() == null ? 0 : this.getEventObjectCatalog().hashCode() );
        result = 37 * result + ( getEventObjectSchema() == null ? 0 : this.getEventObjectSchema().hashCode() );
        result = 37 * result + ( getEventObjectTable() == null ? 0 : this.getEventObjectTable().hashCode() );
        result = 37 * result + ( getIsRollback() == null ? 0 : this.getIsRollback().hashCode() );
        result = 37 * result + ( getJavaClass() == null ? 0 : this.getJavaClass().hashCode() );
        result = 37 * result + ( getNoWait() == null ? 0 : this.getNoWait().hashCode() );
        result = 37 * result + ( getQueueSize() == null ? 0 : this.getQueueSize().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getTriggerCatalog() == null ? 0 : this.getTriggerCatalog().hashCode() );
        result = 37 * result + ( getTriggerName() == null ? 0 : this.getTriggerName().hashCode() );
        result = 37 * result + ( getTriggerSchema() == null ? 0 : this.getTriggerSchema().hashCode() );
         return result;
   }   


}


