// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * UsersId generated by hbm2java
 */
public class UsersId  implements java.io.Serializable {


     private Boolean isAdmin;
     private String remarks;
     private String userName;

    public UsersId() {
    }

    public UsersId(Boolean isAdmin, String remarks, String userName) {
       this.isAdmin = isAdmin;
       this.remarks = remarks;
       this.userName = userName;
    }
   
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersId) ) return false;
		 UsersId castOther = ( UsersId ) other; 
         
		 return ( (this.getIsAdmin()==castOther.getIsAdmin()) || ( this.getIsAdmin()!=null && castOther.getIsAdmin()!=null && this.getIsAdmin().equals(castOther.getIsAdmin()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getIsAdmin() == null ? 0 : this.getIsAdmin().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


