// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private UsersId id;

    public Users() {
    }

    public Users(UsersId id) {
       this.id = id;
    }
   
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }




}


