// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * Views generated by hbm2java
 */
public class Views  implements java.io.Serializable {


     private ViewsId id;

    public Views() {
    }

    public Views(ViewsId id) {
       this.id = id;
    }
   
    public ViewsId getId() {
        return this.id;
    }
    
    public void setId(ViewsId id) {
        this.id = id;
    }




}


