// default package
// Generated May 27, 2025, 6:48:17 AM by Hibernate Tools 6.6.15.Final



/**
 * ViewsId generated by hbm2java
 */
public class ViewsId  implements java.io.Serializable {


     private String checkOption;
     private String insertableInto;
     private String isTriggerDeletable;
     private String isTriggerInsertableInto;
     private String isTriggerUpdatable;
     private String isUpdatable;
     private String remarks;
     private String status;
     private String tableCatalog;
     private String tableName;
     private String tableSchema;
     private String viewDefinition;

    public ViewsId() {
    }

    public ViewsId(String checkOption, String insertableInto, String isTriggerDeletable, String isTriggerInsertableInto, String isTriggerUpdatable, String isUpdatable, String remarks, String status, String tableCatalog, String tableName, String tableSchema, String viewDefinition) {
       this.checkOption = checkOption;
       this.insertableInto = insertableInto;
       this.isTriggerDeletable = isTriggerDeletable;
       this.isTriggerInsertableInto = isTriggerInsertableInto;
       this.isTriggerUpdatable = isTriggerUpdatable;
       this.isUpdatable = isUpdatable;
       this.remarks = remarks;
       this.status = status;
       this.tableCatalog = tableCatalog;
       this.tableName = tableName;
       this.tableSchema = tableSchema;
       this.viewDefinition = viewDefinition;
    }
   
    public String getCheckOption() {
        return this.checkOption;
    }
    
    public void setCheckOption(String checkOption) {
        this.checkOption = checkOption;
    }
    public String getInsertableInto() {
        return this.insertableInto;
    }
    
    public void setInsertableInto(String insertableInto) {
        this.insertableInto = insertableInto;
    }
    public String getIsTriggerDeletable() {
        return this.isTriggerDeletable;
    }
    
    public void setIsTriggerDeletable(String isTriggerDeletable) {
        this.isTriggerDeletable = isTriggerDeletable;
    }
    public String getIsTriggerInsertableInto() {
        return this.isTriggerInsertableInto;
    }
    
    public void setIsTriggerInsertableInto(String isTriggerInsertableInto) {
        this.isTriggerInsertableInto = isTriggerInsertableInto;
    }
    public String getIsTriggerUpdatable() {
        return this.isTriggerUpdatable;
    }
    
    public void setIsTriggerUpdatable(String isTriggerUpdatable) {
        this.isTriggerUpdatable = isTriggerUpdatable;
    }
    public String getIsUpdatable() {
        return this.isUpdatable;
    }
    
    public void setIsUpdatable(String isUpdatable) {
        this.isUpdatable = isUpdatable;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTableCatalog() {
        return this.tableCatalog;
    }
    
    public void setTableCatalog(String tableCatalog) {
        this.tableCatalog = tableCatalog;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getTableSchema() {
        return this.tableSchema;
    }
    
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema;
    }
    public String getViewDefinition() {
        return this.viewDefinition;
    }
    
    public void setViewDefinition(String viewDefinition) {
        this.viewDefinition = viewDefinition;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViewsId) ) return false;
		 ViewsId castOther = ( ViewsId ) other; 
         
		 return ( (this.getCheckOption()==castOther.getCheckOption()) || ( this.getCheckOption()!=null && castOther.getCheckOption()!=null && this.getCheckOption().equals(castOther.getCheckOption()) ) )
 && ( (this.getInsertableInto()==castOther.getInsertableInto()) || ( this.getInsertableInto()!=null && castOther.getInsertableInto()!=null && this.getInsertableInto().equals(castOther.getInsertableInto()) ) )
 && ( (this.getIsTriggerDeletable()==castOther.getIsTriggerDeletable()) || ( this.getIsTriggerDeletable()!=null && castOther.getIsTriggerDeletable()!=null && this.getIsTriggerDeletable().equals(castOther.getIsTriggerDeletable()) ) )
 && ( (this.getIsTriggerInsertableInto()==castOther.getIsTriggerInsertableInto()) || ( this.getIsTriggerInsertableInto()!=null && castOther.getIsTriggerInsertableInto()!=null && this.getIsTriggerInsertableInto().equals(castOther.getIsTriggerInsertableInto()) ) )
 && ( (this.getIsTriggerUpdatable()==castOther.getIsTriggerUpdatable()) || ( this.getIsTriggerUpdatable()!=null && castOther.getIsTriggerUpdatable()!=null && this.getIsTriggerUpdatable().equals(castOther.getIsTriggerUpdatable()) ) )
 && ( (this.getIsUpdatable()==castOther.getIsUpdatable()) || ( this.getIsUpdatable()!=null && castOther.getIsUpdatable()!=null && this.getIsUpdatable().equals(castOther.getIsUpdatable()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getTableCatalog()==castOther.getTableCatalog()) || ( this.getTableCatalog()!=null && castOther.getTableCatalog()!=null && this.getTableCatalog().equals(castOther.getTableCatalog()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getTableSchema()==castOther.getTableSchema()) || ( this.getTableSchema()!=null && castOther.getTableSchema()!=null && this.getTableSchema().equals(castOther.getTableSchema()) ) )
 && ( (this.getViewDefinition()==castOther.getViewDefinition()) || ( this.getViewDefinition()!=null && castOther.getViewDefinition()!=null && this.getViewDefinition().equals(castOther.getViewDefinition()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCheckOption() == null ? 0 : this.getCheckOption().hashCode() );
        result = 37 * result + ( getInsertableInto() == null ? 0 : this.getInsertableInto().hashCode() );
        result = 37 * result + ( getIsTriggerDeletable() == null ? 0 : this.getIsTriggerDeletable().hashCode() );
        result = 37 * result + ( getIsTriggerInsertableInto() == null ? 0 : this.getIsTriggerInsertableInto().hashCode() );
        result = 37 * result + ( getIsTriggerUpdatable() == null ? 0 : this.getIsTriggerUpdatable().hashCode() );
        result = 37 * result + ( getIsUpdatable() == null ? 0 : this.getIsUpdatable().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
        result = 37 * result + ( getTableCatalog() == null ? 0 : this.getTableCatalog().hashCode() );
        result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
        result = 37 * result + ( getTableSchema() == null ? 0 : this.getTableSchema().hashCode() );
        result = 37 * result + ( getViewDefinition() == null ? 0 : this.getViewDefinition().hashCode() );
         return result;
   }   


}


