#!/bin/bash
export CLUSTERNAME=slony_example
export MASTERDBNAME=pgbench
export SLAVEDBNAME=pgbenchslave
export MASTERHOST=127.0.0.1
export MASTERHOST_PORT=5443
export SLAVEHOST=127.0.0.1
export SLAVEHOST_PORT=5444
export REPLICATIONUSER=repl
export PGBENCHUSER=pgbench 
export MST_DB_CNN="-p $MASTERHOST_PORT -h $MASTERHOST -U postgres"
export MST_DB_PGB_CNN="-p $MASTERHOST_PORT -h $MASTERHOST -U $PGBENCHUSER"
export MST_DB_REPL_CNN="-p $MASTERHOST_PORT -h $MASTERHOST -U $REPLICATIONUSER"
export SLV_DB_CNN="-p $SLAVEHOST_PORT -h $SLAVEHOST -U postgres"
export SLV_DB_PGB_CNN="-p $SLAVEHOST_PORT -h $SLAVEHOST -U $PGBENCHUSER "
export SLV_DB_REPL_CNN="-p $SLAVEHOST_PORT -h $SLAVEHOST -U $REPLICATIONUSER " 