spring:
  datasource:
   url: jdbc:mysql://mysql:3306/test
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
   
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
      